import'./year.js';import{categories,scenarioById,scenarios}from'./scenarios.js';import{STORAGE_KEY,addCustom,progressFor,readState,removeCustom,resetScenario,scenarioState,toggleBuiltIn,toggleCustom,writeState}from'./state.js';import{checklistText,copyText}from'./share.js';import{scenarioFromUrl,scenarioUrl}from'./url.js';

const chooser=document.querySelector('#chooser'),manifest=document.querySelector('#manifest'),groups=document.querySelector('#scenario-groups'),status=document.querySelector('#action-status');let state=readState(localStorage,scenarioById);const requestedScenario=new URLSearchParams(location.search).has('for');let active=requestedScenario?scenarioFromUrl(location.search,scenarioById):state.selectedScenario;
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
function persist(){state.selectedScenario=active;writeState(localStorage,state)}
function setUrl(id,replace=false){const url=id?scenarioUrl(id):new URL(location.href);if(!id)url.search='';history[replace?'replaceState':'pushState']({},'',url)}
function announce(message){status.textContent=message;window.clearTimeout(announce.timer);announce.timer=window.setTimeout(()=>status.textContent='',3500)}
function showChooser(push=false){active=null;state.selectedScenario=null;persist();if(push)setUrl(null);manifest.hidden=true;chooser.hidden=false;document.title='Stock-Up Checklist — What Should I Stock Up On?';document.querySelector('#chooser-title').focus();window.scrollTo(0,0)}
function choose(id,{push=true}={}){if(!scenarioById.has(id))return showChooser(push);active=id;persist();if(push)setUrl(id);renderManifest();chooser.hidden=true;manifest.hidden=false;window.scrollTo(0,0);document.querySelector('#manifest-title').focus()}
function renderChooser(){for(const category of categories){const section=el('section','scenario-group');const heading=el('h2','group-title',category);section.append(heading);const grid=el('div','tag-grid');for(const scenario of scenarios.filter(item=>item.category===category)){const button=el('button','scenario-tag');button.type='button';button.dataset.scenario=scenario.id;button.setAttribute('aria-label',`${scenario.title}: ${scenario.description}`);button.append(el('span','tag-code',scenario.code),el('strong','tag-title',scenario.title),el('span','tag-count',`${scenario.sections.reduce((n,s)=>n+s.items.length,0)} ITEMS`));button.addEventListener('click',()=>choose(scenario.id));grid.append(button)}section.append(grid);groups.append(section)}}
function checklistRow(item,checked,type){const row=el('div',`check-row ${type==='custom'?'is-custom':''}`);const input=el('input');input.type='checkbox';input.id=`check-${item.id}`;input.checked=checked;input.dataset.item=item.id;input.dataset.type=type;const label=el('label','item-label',item.label);label.htmlFor=input.id;row.append(input,label);if(type==='custom'){const remove=el('button','remove-item','REMOVE');remove.type='button';remove.dataset.remove=item.id;remove.setAttribute('aria-label',`Remove ${item.label}`);row.append(remove)}return row}
function renderManifest(){const scenario=scenarioById.get(active),current=scenarioState(state,active),checked=new Set(current.checked);document.title=`${scenario.title} Stock-Up Checklist`;document.querySelector('#manifest-code').textContent=scenario.code;document.querySelector('#manifest-title').textContent=scenario.title;document.querySelector('#manifest-description').textContent=scenario.description;const note=document.querySelector('#safety-note');note.textContent=scenario.note;note.hidden=!scenario.note;const list=document.querySelector('#checklist');list.replaceChildren();for(const section of scenario.sections){const block=el('section','check-section');block.dataset.section=section.id;const title=el('h2','section-title',section.title);title.append(el('span','section-qty',String(section.items.length).padStart(2,'0')));block.append(title);for(const item of section.items)block.append(checklistRow(item,checked.has(item.id),'built-in'));list.append(block)}const extras=el('section','check-section extras');extras.id='extras';const extraTitle=el('h2','section-title','My Extras');extraTitle.append(el('span','section-qty',String(current.custom.length).padStart(2,'0')));extras.append(extraTitle);for(const item of current.custom)extras.append(checklistRow(item,item.checked,'custom'));list.append(extras);updateProgress();document.querySelector('#custom-input').value=''}
function updateProgress(){const scenario=scenarioById.get(active),current=scenarioState(state,active),progress=progressFor(scenario,current);document.querySelector('#progress-count').textContent=`${progress.stocked} / ${progress.total} STOCKED`;document.querySelector('#progress-percent').textContent=`${progress.percent}% READY`;const meter=document.querySelector('#progress-meter');meter.value=progress.stocked;meter.max=progress.total;meter.setAttribute('aria-label',`${progress.stocked} of ${progress.total} items stocked, ${progress.percent} percent ready`);document.documentElement.style.setProperty('--progress',`${progress.percent}%`)}
document.querySelector('#checklist').addEventListener('change',event=>{if(!event.target.matches('input[type=checkbox]'))return;const{item,type}=event.target.dataset;if(type==='custom')toggleCustom(state,active,item,event.target.checked);else toggleBuiltIn(state,active,item,event.target.checked);event.target.closest('.check-row').classList.toggle('checked',event.target.checked);persist();updateProgress()});
document.querySelector('#checklist').addEventListener('click',event=>{const button=event.target.closest('[data-remove]');if(!button)return;removeCustom(state,active,button.dataset.remove);persist();renderManifest();announce('Custom item removed.')});
document.querySelector('#add-form').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#custom-input'),item=addCustom(state,active,input.value);if(!item){input.focus();return}persist();renderManifest();document.querySelector('#custom-input').focus();announce(`${item.label} added.`)});
document.querySelector('#switch').addEventListener('click',()=>showChooser(true));
document.querySelector('#reset').addEventListener('click',()=>{if(!confirm(`Reset every check and custom item in ${scenarioById.get(active).title}?`))return;resetScenario(state,active);persist();renderManifest();announce('Checklist reset.')});
document.querySelector('#print').addEventListener('click',()=>window.print());
document.querySelector('#copy').addEventListener('click',async()=>{const text=checklistText(scenarioById.get(active),scenarioState(state,active));try{await copyText(text);announce('Checklist copied.')}catch{const area=el('textarea');area.value=text;area.setAttribute('readonly','');area.className='clipboard-fallback';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();announce(ok?'Checklist copied.':'Copy unavailable — select and copy the list manually.')}});
document.querySelector('#share').addEventListener('click',async()=>{const scenario=scenarioById.get(active),text=checklistText(scenario,scenarioState(state,active));if(navigator.share)try{await navigator.share({title:`${scenario.title} Stock-Up Checklist`,text,url:scenarioUrl(active).href});announce('Checklist shared.');return}catch(error){if(error.name==='AbortError')return}try{await copyText(text);announce('Sharing unavailable; checklist copied instead.')}catch{announce('Sharing is unavailable in this browser.')}});
window.addEventListener('popstate',()=>{const id=scenarioFromUrl(location.search,scenarioById);id?choose(id,{push:false}):showChooser(false)});
renderChooser();if(active&&scenarioById.has(active)){setUrl(active,true);choose(active,{push:false})}else showChooser(false);
export{STORAGE_KEY};
