export const STORAGE_KEY='spw-stock-up-checklist-v1';
export const emptyState=()=>({version:1,selectedScenario:null,scenarios:{}});
const cleanText=value=>String(value??'').replace(/[<>]/g,'').replace(/\s+/g,' ').trim().slice(0,80);
export function builtInIds(scenario){return new Set(scenario.sections.flatMap(section=>section.items.map(item=>item.id)))}
export function normalizeState(input,scenarioById){const result=emptyState();if(!input||typeof input!=='object')return result;const selected=typeof input.selectedScenario==='string'&&scenarioById.has(input.selectedScenario)?input.selectedScenario:null;result.selectedScenario=selected;for(const[id,value]of Object.entries(input.scenarios||{})){const scenario=scenarioById.get(id);if(!scenario||!value||typeof value!=='object')continue;const valid=builtInIds(scenario),checked=[...new Set(Array.isArray(value.checked)?value.checked.filter(item=>typeof item==='string'&&valid.has(item)):[])];const seen=new Set();const custom=[];if(Array.isArray(value.custom))for(const item of value.custom){if(!item||typeof item!=='object'||typeof item.id!=='string'||seen.has(item.id))continue;const label=cleanText(item.label);if(!label)continue;seen.add(item.id);custom.push({id:item.id.slice(0,80),label,checked:Boolean(item.checked)});if(custom.length===50)break}result.scenarios[id]={checked,custom}}return result}
export function readState(storage,scenarioById){try{return normalizeState(JSON.parse(storage.getItem(STORAGE_KEY)||'null'),scenarioById)}catch{return emptyState()}}
export function writeState(storage,state){try{storage.setItem(STORAGE_KEY,JSON.stringify(state));return true}catch{return false}}
export function scenarioState(state,id){return state.scenarios[id]||(state.scenarios[id]={checked:[],custom:[]})}
export function toggleBuiltIn(state,scenarioId,itemId,checked){const current=scenarioState(state,scenarioId),set=new Set(current.checked);checked?set.add(itemId):set.delete(itemId);current.checked=[...set]}
export function addCustom(state,scenarioId,label,id=`custom-${Date.now()}-${Math.random().toString(36).slice(2,8)}`){const text=cleanText(label);if(!text)return null;const item={id,label:text,checked:false};scenarioState(state,scenarioId).custom.push(item);return item}
export function toggleCustom(state,scenarioId,itemId,checked){const item=scenarioState(state,scenarioId).custom.find(entry=>entry.id===itemId);if(item)item.checked=checked}
export function removeCustom(state,scenarioId,itemId){const current=scenarioState(state,scenarioId);current.custom=current.custom.filter(item=>item.id!==itemId)}
export function resetScenario(state,scenarioId){state.scenarios[scenarioId]={checked:[],custom:[]}}
export function progressFor(scenario,current){const total=scenario.sections.reduce((sum,section)=>sum+section.items.length,0)+current.custom.length;const stocked=current.checked.length+current.custom.filter(item=>item.checked).length;return{stocked,total,percent:total?Math.round(stocked/total*100):0}}
