import{spawn}from'node:child_process';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
const base=process.argv[2]||'http://127.0.0.1:4190',chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',profile=await mkdtemp(join(tmpdir(),'ykst-browser-'));const child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--remote-debugging-pipe',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','inherit','pipe','pipe']});let nextId=1,buffer='',sessionId;const pending=new Map(),events=[];child.stdio[4].setEncoding('utf8');child.stdio[4].on('data',chunk=>{buffer+=chunk;let index;while((index=buffer.indexOf('\0'))>=0){const raw=buffer.slice(0,index);buffer=buffer.slice(index+1);if(!raw)continue;const message=JSON.parse(raw);if(message.id&&pending.has(message.id)){const{resolve,reject}=pending.get(message.id);pending.delete(message.id);message.error?reject(new Error(message.error.message)):resolve(message.result)}else events.push(message)}});function send(method,params={},session=sessionId){return new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});child.stdio[3].write(`${JSON.stringify({id,method,params,...(session?{sessionId:session}:{})})}\0`)})}const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));async function evaluate(expression){const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value}async function navigate(path){await send('Page.navigate',{url:base+path});await wait(500)}const check=(value,message)=>{if(!value)throw new Error(message)};
try{const targets=await send('Target.getTargets',{},null),page=targets.targetInfos.find(item=>item.type==='page');sessionId=(await send('Target.attachToTarget',{targetId:page.targetId,flatten:true},null)).sessionId;await send('Page.enable');await send('Runtime.enable');await send('Network.enable');
 await navigate('/');check(await evaluate("!document.querySelector('#empty-state').hidden"),'empty state missing');check(await evaluate("document.querySelector('#results').hidden"),'empty results visible');check(await evaluate("document.querySelector('#draft').value===''"),'draft not initially empty');check(await evaluate("document.documentElement.scrollWidth===document.documentElement.clientWidth"),'desktop overflow');
 await evaluate("document.querySelector('#example').click()");await wait(150);check(await evaluate("!document.querySelector('#results').hidden"),'sample did not analyze');check(await evaluate("document.querySelector('.primary-word').textContent.length>2"),'primary observation absent');check(await evaluate("document.querySelectorAll('#word-list button').length>=1"),'word rankings absent');check(await evaluate("document.querySelectorAll('#phrase-list button').length>=1"),'phrase rankings absent');
 await evaluate("document.querySelector('#word-list button').click()");check(await evaluate("document.querySelectorAll('#review-text mark').length>=2"),'word highlights absent');await evaluate("document.querySelector('#phrase-list button').click()");check(await evaluate("document.querySelectorAll('#review-text mark').length>=3"),'phrase highlights absent');
 await evaluate("Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.__copied=text},configurable:true});document.querySelector('#copy').click()");await wait(80);check((await evaluate('window.__copied')).startsWith('You Keep Saying That'),'copy summary failed');check(!(await evaluate('window.__copied')).includes('The point was simple'),'copy leaked source');
 await evaluate("(()=>{const e=document.querySelector('#draft');e.value='tiny text';e.dispatchEvent(new Event('input',{bubbles:true}))})()");await wait(150);check(await evaluate("!document.querySelector('#short-state').hidden&&document.querySelector('#results').hidden"),'short state failed');
 await evaluate("(()=>{const e=document.querySelector('#draft');e.value=Array.from({length:50},(_,i)=>'unique'+i).join(' ');e.dispatchEvent(new Event('input',{bubbles:true}))})()");await wait(150);check(await evaluate("document.querySelector('#word-list .no-result').textContent.includes('No meaningful')"),'no-repeat state failed');
 const payload='<script>window.__xss=1</script> <img src=x onerror=window.__xss=2> '+Array(45).fill('safe').join(' ');await evaluate(`(()=>{const e=document.querySelector('#draft');e.value=${JSON.stringify(payload)};e.dispatchEvent(new Event('input',{bubbles:true}))})()`);await wait(150);check(await evaluate("window.__xss===undefined"),'pasted script executed');check(await evaluate("document.querySelector('#review-text').textContent.includes('<script>')"),'pasted markup was not preserved as text');check(await evaluate("location.search===''&&location.hash===''"),'draft entered URL');
 await evaluate("document.querySelector('#clear').click()");check(await evaluate("document.querySelector('#draft').value===''&&!document.querySelector('#empty-state').hidden"),'clear failed');await evaluate("document.querySelector('#example').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',text:' ',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await wait(120);check(await evaluate("document.querySelector('#draft').value.length>100"),'keyboard activation failed');
 await navigate('/');check(await evaluate("document.querySelector('#draft').value===''"),'draft persisted across reload');for(const[width,height,mobile]of[[320,700,true],[768,900,true],[1440,900,false],[1920,1080,false]]){await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile});await navigate('/');check(await evaluate("document.documentElement.scrollWidth===document.documentElement.clientWidth"),`${width}px overflow`)}check(await evaluate("Math.min(...[...document.querySelectorAll('button')].filter(x=>x.getClientRects().length).map(x=>x.getBoundingClientRect().height))>=44"),'visible touch target below 44px');await navigate('/privacy/');check((await evaluate('document.title')).startsWith('Privacy'),'privacy failed');await navigate('/missing-page');check((await evaluate('document.title')).startsWith('Page Crossed Out'),'404 failed');
 const errors=events.filter(event=>event.method==='Runtime.consoleAPICalled'&&event.params.type==='error');check(!errors.length,'console errors found');const failed=events.filter(event=>event.method==='Network.loadingFailed');check(!failed.length,'network failures found');const external=events.filter(event=>event.method==='Network.requestWillBeSent').map(event=>new URL(event.params.request.url)).filter(url=>url.origin!==new URL(base).origin&&url.protocol.startsWith('http'));check(!external.length,'external network request found');console.log('Browser QA passed: empty, sample, primary, rankings, word/phrase highlights, editing, short/no-repeat/XSS states, clear, copy, URL and reload privacy, keyboard, 320/768/1440/1920px layouts, privacy, 404, console and network.');
}finally{child.kill('SIGTERM');await rm(profile,{recursive:true,force:true})}
