import{spawn}from'node:child_process';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
const base=process.argv[2]||'http://127.0.0.1:4319',chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',profile=await mkdtemp(join(tmpdir(),'stock-up-browser-'));
const child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--remote-debugging-pipe',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','inherit','pipe','pipe']});let nextId=1,buffer='',sessionId,dialogAccept=false;const pending=new Map(),events=[];
child.stdio[4].setEncoding('utf8');child.stdio[4].on('data',chunk=>{buffer+=chunk;let index;while((index=buffer.indexOf('\0'))>=0){const raw=buffer.slice(0,index);buffer=buffer.slice(index+1);if(!raw)continue;const message=JSON.parse(raw);if(message.id&&pending.has(message.id)){const{resolve,reject}=pending.get(message.id);pending.delete(message.id);message.error?reject(new Error(message.error.message)):resolve(message.result)}else{events.push(message);if(message.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:dialogAccept},message.sessionId)}}});
function send(method,params={},session=sessionId){return new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});child.stdio[3].write(`${JSON.stringify({id,method,params,...(session?{sessionId:session}:{})})}\0`)})}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));async function evaluate(expression){const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text);return result.result.value}async function navigate(path){await send('Page.navigate',{url:base+path});await wait(500)}const check=(condition,message)=>{if(!condition)throw new Error(message)};
try{const targets=await send('Target.getTargets',{},null),page=targets.targetInfos.find(item=>item.type==='page');sessionId=(await send('Target.attachToTarget',{targetId:page.targetId,flatten:true},null)).sessionId;await send('Page.enable');await send('Runtime.enable');
 await navigate('/');check(await evaluate("document.querySelectorAll('.scenario-tag').length")===20,'chooser does not show 20 scenarios');check(await evaluate("document.documentElement.scrollWidth===document.documentElement.clientWidth"),'desktop horizontal overflow');await evaluate("document.querySelector('#chooser-title').focus()");await send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});check(await evaluate("document.activeElement.classList.contains('scenario-tag')"),'keyboard focus did not reach scenario chooser');await evaluate("document.querySelector('[data-scenario=road-trip]').click()");await wait(100);check(await evaluate("document.querySelector('#manifest-title').textContent")==='Road Trip','Road Trip did not open');await evaluate("document.querySelectorAll('#checklist input')[0].click();document.querySelectorAll('#checklist input')[1].click()");check(await evaluate("document.querySelector('#progress-count').textContent")==='2 / 26 STOCKED','progress did not update');
 await evaluate("document.querySelector('#custom-input').value='Spare camera battery';document.querySelector('#add-form').requestSubmit()");check(await evaluate("document.querySelectorAll('.is-custom').length")===1,'custom item was not added');await evaluate("document.querySelector('.is-custom input').click();document.querySelector('#switch').click();document.querySelector('[data-scenario=beach-weekend]').click()");check(await evaluate("document.querySelector('#progress-count').textContent")==='0 / 26 STOCKED','scenario state leaked');
 await evaluate("document.querySelector('#switch').click();document.querySelector('[data-scenario=road-trip]').click()");check(await evaluate("document.querySelector('#progress-count').textContent")==='3 / 27 STOCKED','Road Trip state did not survive switching');await navigate('/?for=road-trip');check(await evaluate("document.querySelector('#progress-count').textContent")==='3 / 27 STOCKED','local persistence did not survive reload');
 await evaluate("Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.__copied=text},configurable:true});document.querySelector('#copy').click()");await wait(100);check((await evaluate("document.querySelector('#action-status').textContent")).includes('copied'),'copy action failed');check((await evaluate("window.__copied")).includes('ROAD TRIP STOCK-UP CHECKLIST'),'copied text was wrong');await evaluate("document.querySelector('.remove-item').click()");check(await evaluate("document.querySelectorAll('.is-custom').length")===0,'custom item did not remove');
 await evaluate("document.querySelector('#reset').click()");await wait(100);check(await evaluate("document.querySelector('#progress-count').textContent")==='2 / 26 STOCKED','cancel reset path failed');dialogAccept=true;await evaluate("document.querySelector('#reset').click()");await wait(100);check(await evaluate("document.querySelector('#progress-count').textContent")==='0 / 26 STOCKED','confirmed reset failed');
 await navigate('/?for=%3Cbad%3E');check(await evaluate("document.querySelector('#chooser').hidden")===false,'malformed URL did not fall back');await send('Emulation.setDeviceMetricsOverride',{width:320,height:700,deviceScaleFactor:1,mobile:true});await navigate('/?for=road-trip');check(await evaluate("document.documentElement.scrollWidth===document.documentElement.clientWidth"),'320px horizontal overflow');check(await evaluate("Math.min(...[...document.querySelectorAll('.check-row')].map(x=>x.getBoundingClientRect().height))")>=44,'mobile checklist targets too short');
 await send('Emulation.setEmulatedMedia',{media:'print'});check(await evaluate("getComputedStyle(document.querySelector('.action-strip')).display")==='none','print actions remain visible');check(await evaluate("getComputedStyle(document.querySelector('.checklist')).display")!=='none','print checklist hidden');await navigate('/privacy/');check((await evaluate('document.title')).startsWith('Privacy'),'privacy page failed');await navigate('/does-not-exist');check((await evaluate('document.title')).startsWith('Manifest Not Found'),'custom 404 failed');const consoleErrors=events.filter(item=>item.method==='Runtime.consoleAPICalled'&&item.params.type==='error');check(consoleErrors.length===0,'console errors found');console.log('Browser QA passed: 20 choices, interaction, progress, custom items, switching, persistence, removal, reset cancel, copy, URLs, 320px, print media, privacy, 404, no console errors.');
}finally{child.kill('SIGTERM');await rm(profile,{recursive:true,force:true})}
