import{DESTINATION_MAP}from'./data.js';import{recommend,preferenceSummary,cravingMatches}from'./scoring.js';const multiStyles=document.createElement('link');multiStyles.rel='stylesheet';multiStyles.href='/multi.css';document.head.append(multiStyles);
const $=s=>document.querySelector(s),steps=[...document.querySelectorAll('.question')],form=$('#trip-form'),intro=$('#intro'),result=$('#result'),direct=$('#direct'),live=$('#live'),cravingGroup=$('[data-key="vibes"]'),cravingNext=$('#craving-next');let step=0,prefs={vibes:[]},seen=[],turn=0,current=null;
function showStep(n){step=n;steps.forEach((el,i)=>{el.hidden=i!==n});$('#progress').textContent=`${String(n+1).padStart(2,'0')} / 03`;steps[n].querySelector('button')?.focus()}
function updateCravings(message=''){const selected=prefs.vibes;cravingGroup.querySelectorAll('button[data-value]').forEach(button=>{const on=selected.includes(button.dataset.value),blocked=selected.length===3&&!on&&button.dataset.value!=='surprise';button.setAttribute('aria-pressed',String(on));button.disabled=blocked;button.setAttribute('aria-disabled',String(blocked))});$('#craving-count').textContent=`${selected.length} / 3 selected`;$('#craving-help').textContent=message;cravingNext.disabled=selected.length===0}
function chooseCraving(value){const selected=prefs.vibes;if(value==='surprise'){prefs.vibes=['surprise'];updateCravings('Surprise Me goes solo.')}else if(selected.includes(value)){prefs.vibes=selected.filter(v=>v!==value);updateCravings()}else{const explicit=selected.filter(v=>v!=='surprise');if(explicit.length===3){updateCravings('Pick up to 3. Deselect one to choose another.');return}prefs.vibes=[...explicit,value];updateCravings(selected.includes('surprise')?'Surprise off. You are back in charge.':'')} }
function choose(button){const group=button.closest('.question'),key=group.dataset.key;if(key==='vibes'){chooseCraving(button.dataset.value);return}prefs[key]=button.dataset.value;group.querySelectorAll('button[data-value]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(step<2)showStep(step+1);else showRecommendation()}
form.addEventListener('click',e=>{const button=e.target.closest('button[data-value]');if(button&&!button.disabled)choose(button)});cravingNext.addEventListener('click',()=>showStep(2));
function text(selector,value){$(selector).textContent=value}
function showRecommendation(){current=recommend(prefs,{seen,turn});seen.push(current.id);turn++;intro.hidden=true;direct.hidden=true;form.hidden=true;result.hidden=false;result.style.setProperty('--ink',current.colors[1]);result.style.setProperty('--accent',current.colors[0]);text('#destination',current.place.toUpperCase());text('#country',current.country.toUpperCase());text('#pitch',current.pitch);text('#you-said',`You said: ${preferenceSummary(prefs)}.`);const matched=cravingMatches(current,prefs);const matchLead=prefs.vibes.includes('surprise')?'It fits the time, pace and season you gave us.':matched.length===prefs.vibes.length?'It hits every craving you picked.':`It strongly covers ${matched.map(v=>v.replace('sun','sun and beach')).join(' + ')} — the best overlap for this combination.`;text('#why',`${matchLead} ${current.why}`);current.moves.forEach((move,i)=>text(`#move-${i+1}`,move));text('#eat',current.eat);text('#note',current.note);result.classList.remove('arrive');requestAnimationFrame(()=>result.classList.add('arrive'));live.textContent=`Go to ${current.place}, ${current.country}. ${current.pitch}`;history.replaceState(null,'',location.pathname)}
$('#again').addEventListener('click',showRecommendation);
function reset(){prefs={vibes:[]};seen=[];turn=0;current=null;result.hidden=true;direct.hidden=true;intro.hidden=false;form.hidden=true;form.querySelectorAll('[aria-pressed]').forEach(b=>b.setAttribute('aria-pressed','false'));updateCravings();history.replaceState(null,'',location.pathname);showStep(0);live.textContent='Preferences reset.'}
$('#start-over').addEventListener('click',reset);$('#begin-direct').addEventListener('click',reset);$('#start').addEventListener('click',()=>{intro.hidden=true;form.hidden=false;showStep(0)});
async function share(){const url=new URL(location.href);url.search='';url.searchParams.set('to',current.id);const shareText=`This website just sent me to ${current.place}. Apparently I need to go.`;try{if(navigator.share)await navigator.share({title:`Go to ${current.place}`,text:shareText,url:url.href});else{await navigator.clipboard.writeText(`${shareText}\n${url.href}`);text('#share-feedback','Copied. Send the good news.')}}catch(error){if(error.name!=='AbortError')text('#share-feedback','Could not share — copy the address from your browser.')}}
$('#share').addEventListener('click',share);
const raw=new URLSearchParams(location.search).get('to');if(raw&&/^[a-z0-9-]{2,40}$/.test(raw)&&DESTINATION_MAP.has(raw)){const d=DESTINATION_MAP.get(raw);intro.hidden=true;form.hidden=true;result.hidden=true;direct.hidden=false;text('#direct-place',d.place.toUpperCase());text('#direct-country',d.country.toUpperCase());text('#direct-pitch',d.pitch);direct.style.setProperty('--ink',d.colors[1]);direct.style.setProperty('--accent',d.colors[0])}else{if(raw)history.replaceState(null,'',location.pathname);form.hidden=true;result.hidden=true;direct.hidden=true}updateCravings();
