import{DESTINATIONS}from'./data.js';
const season=(d,m)=>d.seasons.includes(m)?5:d.seasons.some(x=>Math.min((x-m+12)%12,(m-x+12)%12)===1)?1:-7;
const selected=p=>p.vibes||[p.vibe].filter(Boolean);
export function cravingMatches(d,p){const vibes=selected(p);return vibes.includes('surprise')?[]:vibes.filter(v=>d.vibes.includes(v))}
export function scoreDestination(d,p,month){const wanted=selected(p),matches=cravingMatches(d,p);let s=0;s+=d.lengths.includes(p.length)?12:-10;s+=wanted.includes('surprise')?Math.min(d.vibes.length,4):matches.length*9-(wanted.length-matches.length)*2;if(matches.length===wanted.length&&wanted.length>1)s+=4;if(matches.length>=2)s+=3;s+=d.energy.includes(p.energy)?7:-5;s+=season(d,month);if(wanted.includes('sun')&&[11,12,1,2].includes(month)&&d.seasons.includes(month))s+=5;if(p.length==='week'&&d.lengths.includes('week'))s+=3;if(p.length==='weekend'&&d.lengths.length===1)s+=2;return s}
function hash(text){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function rankedDestinations(preferences,month=new Date().getMonth()+1){return DESTINATIONS.map(destination=>({destination,score:scoreDestination(destination,preferences,month),matches:cravingMatches(destination,preferences)})).sort((a,b)=>b.score-a.score||b.matches.length-a.matches.length||a.destination.id.localeCompare(b.destination.id))}
export function candidateBand(preferences,month=new Date().getMonth()+1,excluded=[]){const wanted=selected(preferences),ranked=rankedDestinations(preferences,month);let pool=ranked.filter(x=>!excluded.includes(x.destination.id)&&x.destination.lengths.includes(preferences.length));if(!wanted.includes('surprise')){const maxMatches=Math.max(...pool.map(x=>x.matches.length));pool=pool.filter(x=>x.matches.length>=Math.max(1,maxMatches-1))}if(!pool.length)pool=ranked.filter(x=>!excluded.includes(x.destination.id));const best=pool[0]?.score??0;let band=pool.filter(x=>x.score>=best-5).slice(0,24);if(band.length<10)band=pool.slice(0,Math.min(12,pool.length));return band}
export function recommend(preferences,{month=new Date().getMonth()+1,seen=[],turn=0}={}){let band=candidateBand(preferences,month,seen);if(!band.length)band=candidateBand(preferences,month,[]);const seed=`${preferences.length}|${selected(preferences).join('+')}|${preferences.energy}|${month}|${turn}|${seen.join(',')}`;return band[hash(seed)%band.length].destination}
export function preferenceSummary(p){const lengths={weekend:'a weekend','four-five':'four or five days',week:'a full week'},labels={food:'food',sun:'sun and beach',culture:'culture and history',nature:'nature',nightlife:'nightlife',mountains:'mountains',romantic:'romance',relax:'a slow pace',adventure:'adventure',architecture:'architecture',charming:'somewhere small and charming',weird:'something different',hidden:'a hidden gem',islands:'island time',scenic:'serious scenery',surprise:'a genuine surprise'},energies={easy:'an easy pace',balanced:'room to explore',adventure:'some adventure'};return `${lengths[p.length]}, ${selected(p).map(v=>labels[v]).join(' + ')} and ${energies[p.energy]}`}
