const sets={
mountains:'madeira azores bergen oslo brasov ohrid kotor sofia crete madeira faroe-islands lake-bled durmitor slovak-paradise transylvania sarajevo-mountains shetland isle-of-skye ronda mallorca tenerife andorra dolomites picos-europa peneda-geres snowdonia lake-district killarney lofoten abisko hallstatt-region bohinj zagori kazbegi chamonix appenzell fussen rila tatras la-gomera isle-of-arran'.split(' '),
romantic:'porto seville san-sebastian granada lisbon edinburgh galway copenhagen stockholm tallinn vilnius gdansk prague vienna graz ljubljana budapest mostar split dubrovnik kotor ohrid athens corfu milos lecce matera lyon strasbourg bordeaux ghent lucerne sintra coimbra annecy cagliari florence verona siena lake-como bruges colmar nice york dingle lake-district hydra hallstatt-region amorgos comporta formentera menton lausanne quedlinburg cesky-krumlov nafplio'.split(' '),
relax:'bath san-sebastian valencia madeira'.split(' '),
architecture:'porto bologna seville granada lisbon bilbao edinburgh copenhagen stockholm helsinki tallinn riga vilnius gdansk wroclaw prague brno vienna graz ljubljana budapest sarajevo mostar split dubrovnik zagreb kotor sofia plovdiv bucharest sibiu athens naples palermo turin lecce trieste matera lyon strasbourg lille antwerp ghent rotterdam berlin hamburg leipzig munich salzburg lucerne sintra coimbra cagliari ravenna perugia florence verona siena orvieto girona salamanca santiago bruges colmar nantes nice alesund kosice meteora syros berat gjirokaster veliko-tarnovo nuremberg quedlinburg lausanne arles-camargue'.split(' '),
charming:'porto san-sebastian granada braga bath galway tallinn vilnius gdansk wroclaw brno graz ljubljana mostar zagreb kotor ohrid plovdiv brasov sibiu naxos corfu milos lecce matera strasbourg ghent utrecht luxembourg salzburg lucerne ronda menorca coimbra ravenna perugia annecy sintra cork saaremaa florence verona siena lucca orvieto girona cadiz santiago aveiro bruges dinant colmar york dingle gotland parnu bratislava banska-stiavnica hydra berat prizren maramures radovljica freiburg quedlinburg guernsey fussen skofja-loka cesky-krumlov menton'.split(' '),
hidden:'braga belfast galway gothenburg riga vilnius wroclaw brno graz ljubljana sarajevo mostar zagreb tirana ohrid sofia plovdiv brasov sibiu thessaloniki turin lecce trieste matera lille antwerp ghent utrecht luxembourg leipzig coimbra ravenna perugia annecy ronda saaremaa curonian-spit poznan kotor-bay lucca orvieto cadiz picos-europa evora aveiro peneda-geres dinant dijon nantes bristol dingle aarhus tartu parnu bratislava banska-stiavnica kosice zagori syros berat gjirokaster prizren maramures chisinau radovljica freiburg quedlinburg guernsey isle-of-man saxon-switzerland veliko-tarnovo rugen hebrides achill samothrace lesvos comporta la-gomera el-hierro gozo skofja-loka moravian-karst saimaa luxembourg-ardennes'.split(' '),
islands:'madeira azores crete naxos corfu milos mallorca menorca tenerife lanzarote malta cyprus faroe-islands shetland isle-of-skye sardinia-east porto-santo saaremaa funchal cagliari corsica bornholm lofoten gotland syros hydra vis guernsey jersey isle-of-man hebrides achill samothrace lesvos amorgos la-gomera el-hierro formentera gozo svalbard isle-of-arran kefalonia sao-miguel-east'.split(' ')
};
sets.relax.push(...'madeira valencia lisbon braga bath copenhagen gothenburg oslo helsinki tallinn vilnius ljubljana zagreb ohrid corfu naxos turin lecce strasbourg bordeaux ghent utrecht lucerne annecy menorca mallorca malta cyprus algarve porto-santo saaremaa curonian-spit coimbra lucca lake-como cadiz evora aveiro dingle lake-district bornholm gotland parnu bratislava hallstatt-region bohinj hydra novi-sad maramures andorra guernsey jersey rugen achill lesvos amorgos comporta formentera gozo saimaa isle-of-arran brittany-coast peak-district luxembourg-ardennes'.split(' '));
const maps=Object.fromEntries(Object.entries(sets).map(([trait,ids])=>[trait,new Set(ids)]));
export function enrichVibes(destination){const vibes=new Set(destination.vibes);if(destination.energy.includes('adventure')&&(vibes.has('nature')||vibes.has('weird')))vibes.add('adventure');if(vibes.has('nature')||vibes.has('sun'))vibes.add('scenic');for(const[trait,ids]of Object.entries(maps))if(ids.has(destination.id))vibes.add(trait);return[...vibes]}
