import test from'node:test';import assert from'node:assert/strict';import{makePlan,normalizeConfig,configKey}from'../src/js/engine.js';import{encodeConfig,decodeConfig}from'../src/js/url.js';
const base={guests:20,kids:0,party:'house',duration:'medium',food:'finger',drinks:['water','soft'],venue:'home',cake:false,decorations:false,disposable:true};const by=(p,id)=>p.items.find(x=>x.id===id);
test('normalizes hostile configuration safely',()=>{const c=normalizeConfig({guests:Infinity,kids:-8,party:'nope',drinks:['beer','beer','evil']});assert.equal(c.guests,24);assert.equal(c.kids,0);assert.deepEqual(c.drinks,['beer'])});
test('guest count materially scales quantities',()=>{const a=makePlan({...base,guests:10}),b=makePlan({...base,guests:80});assert.ok(by(b,'finger').value.low>by(a,'finger').value.low*5);assert.ok(by(b,'bin-bags').value.low>by(a,'bin-bags').value.low)});
test('duration changes consumables but not fixed tools',()=>{const a=makePlan({...base,duration:'short'}),b=makePlan({...base,duration:'long'});assert.ok(by(b,'water').value.low>by(a,'water').value.low);assert.equal(by(a,'bottle-opener').quantity,by(b,'bottle-opener').quantity)});
test('food, drinks, party, cake and venue are contextual',()=>{const bbq=makePlan({...base,food:'bbq',venue:'garden',party:'bbq'}),meal=makePlan({...base,food:'meal',venue:'rented',party:'dinner',drinks:['water','wine'],cake:true});assert.ok(by(bbq,'bbq-main'));assert.equal(by(bbq,'meal'),undefined);assert.ok(by(bbq,'bug'));assert.ok(by(meal,'chairs'));assert.ok(by(meal,'cake'));assert.ok(by(meal,'corkscrew'));assert.equal(by(meal,'beer'),undefined)});
test('alcohol-free plan contains no alcohol items',()=>{const p=makePlan({...base,drinks:['water','soft']});for(const id of['beer','wine','spirits','mixers','garnish','corkscrew'])assert.equal(by(p,id),undefined)});
test('all numeric ranges are finite positive ordered and ids stable unique',()=>{const p=makePlan({...base,guests:300,duration:'long',food:'bbq',drinks:['water','soft','beer','wine','cocktails'],venue:'park',cake:true,decorations:true});assert.equal(new Set(p.items.map(x=>x.id)).size,p.items.length);for(const i of p.items){assert.ok(i.quantity&&!/NaN|Infinity|^0\b/.test(i.quantity));if(i.value&&'low'in i.value){assert.ok(Number.isFinite(i.value.low)&&Number.isFinite(i.value.high));assert.ok(i.value.low>0&&i.value.low<=i.value.high)}}assert.equal(configKey(p.config),configKey(p.config))});
test('URL round trips configuration and malformed state is safe',()=>{const c=normalizeConfig(base),token=encodeConfig(c),decoded=decodeConfig(`?plan=${token}`);assert.deepEqual(decoded,c);for(const s of['?plan=%3Cscript%3E','?plan=___','?plan='+('a'.repeat(600))])assert.equal(decodeConfig(s),null)});
