import test from'node:test';import assert from'node:assert/strict';import{createSession,pointsFor,shuffled}from'../src/js/game.js';
const data=Array.from({length:4},(_,i)=>({id:`p${i}`,category:i<3?'A':'B',hints:['1','2','3','4','5']}));
test('points are transparent',()=>assert.deepEqual([1,2,3,4,5].map(pointsFor),[5,4,3,2,1]));
test('hint progression stops at five',()=>{const g=createSession(data,()=>.2);g.start();for(let i=0;i<10;i++)g.nextHint();assert.equal(g.hint,5)});
test('claim, yes, and no update stats',()=>{const g=createSession(data,()=>.2);g.start();g.nextHint();g.know();g.judge(true);assert.deepEqual(g.stats,{played:1,solved:1,score:4,hintsTotal:2,best:2});g.start();g.know();g.judge(false);assert.equal(g.stats.played,2);assert.equal(g.stats.score,4)});
test('give up only works on hint five',()=>{const g=createSession(data);g.start();g.giveUp();assert.equal(g.phase,'playing');while(g.hint<5)g.nextHint();g.giveUp();assert.equal(g.intent,'gave-up');assert.equal(g.stats.played,1)});
test('deck reaches all puzzles before refill and avoids boundary repeat',()=>{const g=createSession(data,()=>0);const ids=[];for(let i=0;i<4;i++){ids.push(g.start().id);g.phase='result'}assert.equal(new Set(ids).size,4);const prior=ids.at(-1);g.start();assert.notEqual(g.current.id,prior)});
test('category rebuilds deck from eligible puzzles',()=>{const g=createSession(data,()=>0);g.setCategory('B');assert.equal(g.start().id,'p3')});
test('specific puzzle bypasses deck safely',()=>{const g=createSession(data);assert.equal(g.start(data[2]).id,'p2')});
test('specific shared puzzle is excluded from the following deck',()=>{const g=createSession(data,()=>0);g.start(data[2]);for(let i=0;i<3;i++){g.phase='result';g.start();assert.notEqual(g.current.id,'p2')}});
test('shuffle preserves every item',()=>assert.deepEqual(shuffled([1,2,3],()=>0).sort(),[1,2,3]));
test('share is spoiler free',()=>{const g=createSession(data);g.start(data[0]);g.know();g.judge(true);const text=g.shareText('https://game.test/?p=p0');assert.match(text,/Got it after 1 hint/);assert.doesNotMatch(text,/undefined|p0.*p0/)});
