import{COUNTRIES}from'../data/countries.js';import{PLUG_TYPES,assess}from'./engine.js';
const $=s=>document.querySelector(s),country=$('#country'),list=$('#country-list'),form=$('#checker'),result=$('#result');let selected=null,active=-1;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function matches(q){q=q.trim().toLowerCase();return(q?COUNTRIES.filter(c=>[c.name,...c.aliases].some(x=>x.toLowerCase().includes(q))):COUNTRIES).slice(0,40)}
function showList(){const rows=matches(country.value);list.replaceChildren(...rows.map((c,i)=>{const li=document.createElement('li');li.role='option';li.id=`country-${i}`;li.dataset.id=c.id;li.textContent=c.name;li.addEventListener('pointerdown',e=>{e.preventDefault();choose(c)});return li}));list.hidden=!rows.length;country.setAttribute('aria-expanded',String(!!rows.length));active=-1}
function choose(c){selected=c;country.value=c.name;list.hidden=true;country.setAttribute('aria-expanded','false');$('#country-status').textContent=`${c.voltages.join(' / ')} V · ${c.frequencies.join(' / ')} Hz · socket ${c.plugs.join(', ')}`}
country.addEventListener('input',()=>{selected=null;showList()});country.addEventListener('focus',showList);country.addEventListener('blur',()=>setTimeout(()=>{list.hidden=true;country.setAttribute('aria-expanded','false')},120));country.addEventListener('keydown',e=>{const items=[...list.children];if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();active=(active+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;items.forEach((x,i)=>x.setAttribute('aria-selected',String(i===active)));country.setAttribute('aria-activedescendant',items[active]?.id||'')}else if(e.key==='Enter'&&active>=0){e.preventDefault();choose(COUNTRIES.find(c=>c.id===items[active].dataset.id))}else if(e.key==='Escape'){list.hidden=true;country.setAttribute('aria-expanded','false')}});
export const PLUG_DESCRIPTIONS={A:'two parallel flat blades',B:'two parallel flat blades and a round ground pin',C:'two round pins',D:'three large round pins in a triangle',E:'two round pins with an earth-pin aperture',F:'two round pins with side earthing contacts',G:'three rectangular pins in a triangle',H:'three round pins in the modern Israeli arrangement',I:'two angled flat pins and a vertical ground pin',J:'three round pins in the Swiss offset arrangement',K:'two round pins and a projecting ground pin',L:'three round pins in a straight line',M:'three extra-large round pins in a wide triangle',N:'three compact round pins in the IEC 60906-1 arrangement',O:'three round pins in the wider Thai arrangement'};
for(const type of PLUG_TYPES){const description=PLUG_DESCRIPTIONS[type],label=document.createElement('label');label.setAttribute('aria-label',`Type ${type} — ${description}`);label.innerHTML=`<input type="radio" name="plug" value="${type}"><svg class="plug-icon" viewBox="0 0 72 64" aria-hidden="true"><use href="/assets/plug-types.svg#plug-${type.toLowerCase()}"></use></svg><b>TYPE ${type}</b><span class="sr-only">${description}</span>`;$('#plugs').append(label)}
$('#voltage-mode').addEventListener('change',e=>{const range=e.target.value==='range';$('#max-wrap').hidden=!range;$('#vmin-label').textContent=range?'From':'Voltage'});$('#unknown').addEventListener('change',e=>{$('#rating-fields').hidden=e.target.checked});
const text={direct:['PASS','YES — YOU CAN PLUG IT IN','NOTHING EXTRA','The entered rating covers every published destination voltage and frequency, and the confirmed plug type is listed for the destination.'],adapter:['ADAPTER','YES — WITH A PLUG ADAPTER','ADAPTER ONLY','The entered rating covers the local voltage and frequency. The confirmed plug shape is not listed for the destination. A plug adapter does not convert electricity.'], 'voltage-stop':['STOP','NO — NOT DIRECTLY','VOLTAGE CONVERSION REQUIRES CHECKING','The device rating does not cover the destination voltage. A plug adapter alone is not sufficient. Any conversion equipment must match the required voltage, device power, and manufacturer instructions.'], 'voltage-frequency-stop':['STOP','NO — NOT DIRECTLY','VOLTAGE AND FREQUENCY DO NOT MATCH','Both electrical checks fail. A plug adapter alone is not sufficient, and a transformer does not normally change frequency.'],check:['CHECK','CHECK BEFORE USING','LOCAL SUPPLY OR DEVICE REQUIREMENTS VARY','The entered information does not support an unconditional yes. Confirm the actual local supply and the manufacturer’s frequency requirements before use.'],unknown:['HOLD',"CAN'T TELL YET",'CHECK THE LABEL FIRST',"We can’t determine voltage compatibility without the device input rating. Look for INPUT on the charger, power brick, device label, or near the power inlet." ]};
function mark(value){return value==='compatible'?'✓ COMPATIBLE':value==='adapter'?'✕ DOES NOT FIT':value==='incompatible'?'✕ MISMATCH':'? VARIES'}
function paramsFor(r){const p=new URLSearchParams({to:r.country.id,plug:r.device.plug,vmin:r.device.voltageMin,vmax:r.device.voltageMax,f:r.device.frequencies.join(',')});return p.toString()}
function render(r,push=true){const t=text[r.state]||text.unknown;result.dataset.state=r.state;$('#stamp').textContent=t[0];$('#verdict').textContent=t[1];$('#need').textContent=t[2];$('#explanation').textContent=t[3];const unknown=r.state==='unknown';$('.checks').hidden=unknown;$('#assumptions').hidden=unknown;if(!unknown){$('#voltage-check').textContent=mark(r.voltage);$('#frequency-check').textContent=mark(r.frequency);$('#plug-check').textContent=mark(r.plug);$('#assumptions').textContent=`DEVICE ${r.device.voltageMin}${r.device.voltageMax!==r.device.voltageMin?'–'+r.device.voltageMax:''} V · ${r.device.frequencies.join('/')} Hz · TYPE ${r.device.plug}  /  ${r.country.name.toUpperCase()} ${r.country.voltages.join('/')} V · ${r.country.frequencies.join('/')} Hz · SOCKET ${r.country.plugs.join(', ')}`;if(push)history.replaceState(null,'',`?${paramsFor(r)}`)}result.hidden=false;result.focus();return r}
form.addEventListener('submit',e=>{e.preventDefault();$('#form-error').textContent='';if($('#unknown').checked)return render({state:'unknown'});const plug=$('input[name=plug]:checked');if(!selected||!plug){$('#form-error').textContent='Choose a destination and confirm your plug type.';return}const min=$('#vmin').value,max=$('#voltage-mode').value==='range'?$('#vmax').value:min,f=$('input[name=frequency]:checked').value.split(',').map(Number),r=assess({voltageMin:min,voltageMax:max,frequencies:f,plug:plug.value},selected);if(r.state==='invalid'){$('#form-error').textContent='Enter a valid voltage from 1–300 V. For a range, “from” must not exceed “to”.';return}render(r)});
$('#edit').addEventListener('click',()=>{form.scrollIntoView({behavior:'smooth'});country.focus()});$('#share').addEventListener('click',async()=>{const data={title:'Can I Plug This In?',text:$('#verdict').textContent,url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);$('#share-status').textContent='Result link copied.'}}catch(e){if(e.name!=='AbortError')$('#share-status').textContent='Could not share this link.'}});
function fromUrl(){const p=new URLSearchParams(location.search);if(!p.size)return;const c=COUNTRIES.find(x=>x.id===p.get('to')),plug=p.get('plug'),vmin=p.get('vmin'),vmax=p.get('vmax'),freq=p.get('f')?.split(',').map(Number);const r=assess({voltageMin:vmin,voltageMax:vmax,frequencies:freq,plug},c);if(r.state==='invalid')return;selected=c;country.value=c.name;$('#vmin').value=vmin;$('#vmax').value=vmax;$(`input[name=plug][value="${CSS.escape(plug)}"]`).checked=true;const fr=$(`input[name=frequency][value="${CSS.escape(freq.join(','))}"]`);if(fr)fr.checked=true;choose(c);render(r,false)}fromUrl();
