import{MIN_YEAR,MAX_YEAR,formatDate,fromLocalDate,moveDay,parseDate,relativeCopy,toISODate,weekdayName}from'./calendar.js';
const byId=id=>document.getElementById(id);let selected;
export function getLocalToday(now=new Date()){return fromLocalDate(now)}
export function dateFromSearch(search,today){const params=new URLSearchParams(search);return parseDate(params.get('date'))||today}
export function shareCopy(date){return`${formatDate(date)} is a ${weekdayName(date)}.`}
export function render(date,today=getLocalToday()){selected=date;const iso=toISODate(date),weekday=weekdayName(date);byId('date-input').value=iso;byId('weekday').textContent=weekday.toUpperCase();byId('chosen-date').textContent=formatDate(date).toUpperCase();byId('relative').textContent=relativeCopy(date,today);byId('prev').disabled=!moveDay(date,-1);byId('next').disabled=!moveDay(date,1);byId('today').disabled=iso===toISODate(today);byId('result').dataset.day=weekday.toLowerCase();return{iso,weekday}}
function syncUrl(date){const url=new URL(location.href);url.searchParams.set('date',toISODate(date));history.replaceState(null,'',url)}
function choose(date){render(date);syncUrl(date)}
export async function share(date=selected){const text=shareCopy(date),url=new URL(location.href);url.searchParams.set('date',toISODate(date));try{if(navigator.share)await navigator.share({title:'What Day Is This Date?',text,url:url.href});else{await navigator.clipboard.writeText(`${text} ${url.href}`);byId('share-status').textContent='Copied result and link.'}}catch(error){if(error?.name!=='AbortError')byId('share-status').textContent='Could not share. Copy the address from your browser.'}}
export function init(now=new Date()){const today=getLocalToday(now);selected=dateFromSearch(location.search,today);render(selected,today);byId('date-input').addEventListener('change',event=>{const date=parseDate(event.target.value);if(date){choose(date);byId('date-error').textContent=''}else byId('date-error').textContent=`Choose a valid date from ${MIN_YEAR} to ${MAX_YEAR}.`});byId('prev').addEventListener('click',()=>{const date=moveDay(selected,-1);if(date)choose(date)});byId('next').addEventListener('click',()=>{const date=moveDay(selected,1);if(date)choose(date)});byId('today').addEventListener('click',()=>choose(getLocalToday()));byId('share').addEventListener('click',()=>share());addEventListener('popstate',()=>render(dateFromSearch(location.search,getLocalToday())));scheduleMidnight()}
function scheduleMidnight(){const now=new Date(),next=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1,0,0,1);setTimeout(()=>{render(selected,getLocalToday());scheduleMidnight()},Math.min(next-now,2147483647))}
if(typeof document!=='undefined')init();
