import{PARTY_TYPES,DURATIONS,FOOD_TYPES,DRINK_TYPES,VENUES,DEFAULT_CONFIG}from'./data.js';import{makePlan,configKey,normalizeConfig}from'./engine.js';import{load,save,clear}from'./storage.js';import{encodeConfig,decodeConfig}from'./url.js';
const $=s=>document.querySelector(s),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};let plan,state,key;
function options(name,map,type='radio'){const wrap=$(`#${name}-options`);for(const[id,label]of Object.entries(map)){const l=el('label','choice'),i=el('input');i.type=type;i.name=name;i.value=id;l.append(i,el('span','',label));wrap.append(l)}}options('party',PARTY_TYPES);options('duration',DURATIONS);[...$('#duration-options').querySelectorAll('span')].forEach((x,i)=>x.textContent=Object.values(DURATIONS)[i].label);options('food',FOOD_TYPES);options('drinks',DRINK_TYPES,'checkbox');options('venue',VENUES);
function setForm(c){$('#guests').value=c.guests;$('#kids').value=c.kids;for(const name of['party','duration','food','venue']){const n=document.querySelector(`[name=${name}][value="${c[name]}"]`);if(n)n.checked=true}for(const n of document.querySelectorAll('[name=drinks]'))n.checked=c.drinks.includes(n.value);for(const name of['cake','decorations','disposable'])$(`#${name}`).checked=c[name]}
function readForm(){return normalizeConfig({guests:+$('#guests').value,kids:+$('#kids').value,party:$('[name=party]:checked')?.value,duration:$('[name=duration]:checked')?.value,food:$('[name=food]:checked')?.value,drinks:[...document.querySelectorAll('[name=drinks]:checked')].map(x=>x.value),venue:$('[name=venue]:checked')?.value,cake:$('#cake').checked,decorations:$('#decorations').checked,disposable:$('#disposable').checked})}
function row(item,custom=false){const label=el('label','buy-row'),box=el('input');box.type='checkbox';box.checked=state.x.has(item.id);box.dataset.id=item.id;const body=el('span','row-main'),top=el('span','row-top');top.append(el('b','',item.name),el('strong','',item.quantity||''));body.append(top);if(item.note)body.append(el('small','',item.note));label.append(box,body);if(custom){const remove=el('button','remove','Remove');remove.type='button';remove.dataset.remove=item.id;remove.setAttribute('aria-label',`Remove ${item.name}`);label.append(remove)}return label}
function progress(){const total=plan.items.length+state.custom.length,done=[...state.x].filter(id=>plan.items.some(x=>x.id===id)||state.custom.some(x=>x.id===id)).length;$('#progress-text').textContent=`${done} of ${total} sorted`;$('#progress').max=total||1;$('#progress').value=done;$('#progress-percent').textContent=`${Math.round(done/(total||1)*100)}%`;}
function render(){const list=$('#list');list.replaceChildren();for(const[category,items]of Object.entries(plan.groups)){const section=el('section','list-section');const h=el('h2');h.append(el('span','',category),el('small','',String(items.length).padStart(2,'0')));section.append(h,...items.map(x=>row(x)));list.append(section)}if(state.custom.length){const section=el('section','list-section custom-section'),h=el('h2');h.append(el('span','','My additions'),el('small','',String(state.custom.length).padStart(2,'0')));section.append(h,...state.custom.map(x=>row(x,true)));list.append(section)}progress()}
function showPlan(c,push=true){plan=makePlan(c);key=configKey(plan.config);state=load(key);$('#planner').hidden=true;$('#result').hidden=false;$('#party-summary').textContent=`${plan.config.guests} guests · ${PARTY_TYPES[plan.config.party]} · ${DURATIONS[plan.config.duration].label} · ${VENUES[plan.config.venue]}`;render();if(push)history.replaceState(null,'',`?plan=${encodeConfig(plan.config)}`);$('#result-title').focus();scrollTo({top:0,behavior:'smooth'})}
$('#brief').addEventListener('submit',e=>{e.preventDefault();showPlan(readForm())});$('#edit').addEventListener('click',()=>{$('#result').hidden=true;$('#planner').hidden=false;setForm(plan.config);history.replaceState(null,'',location.pathname);$('#planner-title').focus()});$('#list').addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;e.target.checked?state.x.add(e.target.dataset.id):state.x.delete(e.target.dataset.id);save(key,state);progress()});$('#list').addEventListener('click',e=>{const id=e.target.dataset.remove;if(!id)return;state.custom=state.custom.filter(x=>x.id!==id);state.x.delete(id);save(key,state);render();status('Custom item removed.')});
$('#add-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#custom-name').value.trim(),quantity=$('#custom-quantity').value.trim();if(!name)return;const id=`custom-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;state.custom.push({id,name:name.slice(0,80),quantity:quantity.slice(0,30)});save(key,state);e.currentTarget.reset();render();$(`[data-id="${id}"]`).focus();status(`${name.slice(0,80)} added.`)});
function textList(){const lines=['PARTY BUY LIST',`${plan.config.guests} guests · ${PARTY_TYPES[plan.config.party]} · ${DURATIONS[plan.config.duration].label}`,''];for(const[cat,items]of Object.entries(plan.groups)){lines.push(cat.toUpperCase());for(const x of items)lines.push(`[${state.x.has(x.id)?'x':' '}] ${x.name} — ${x.quantity}`);lines.push('')}if(state.custom.length){lines.push('MY ADDITIONS');for(const x of state.custom)lines.push(`[${state.x.has(x.id)?'x':' '}] ${x.name}${x.quantity?` — ${x.quantity}`:''}`)}return lines.join('\n')}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);status(msg)}catch{const area=el('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove();status(msg)}}$('#copy').addEventListener('click',()=>copy(textList(),'Buy list copied.'));$('#print').addEventListener('click',()=>print());$('#share').addEventListener('click',async()=>{const url=`${location.origin}${location.pathname}?plan=${encodeConfig(plan.config)}`;try{if(navigator.share){await navigator.share({title:'Party Buy List',text:`Shopping plan for ${plan.config.guests} guests`,url});status('Share sheet opened.')}else await copy(url,'Plan link copied.')}catch(e){if(e.name!=='AbortError')await copy(url,'Plan link copied.')}});$('#reset').addEventListener('click',()=>{if(!confirm('Reset every checkmark for this party? Custom items will stay.'))return;state.x.clear();clear(key);save(key,state);render();status('Checklist reset.')});function status(s){$('#status').textContent=s;clearTimeout(status.timer);status.timer=setTimeout(()=>$('#status').textContent='',3500)}
document.querySelector('[data-year]').textContent=new Date().getFullYear();const shared=decodeConfig(location.search);setForm(shared||DEFAULT_CONFIG);if(shared)showPlan(shared,false);
