export const PARTY_TYPES={birthday:'Birthday',house:'House party',dinner:'Dinner party',bbq:'BBQ / cookout',kids:'Kids’ party',game:'Game night',watch:'Watch party',cocktail:'Cocktail party',celebration:'Graduation / celebration',casual:'Casual gathering'};
export const DURATIONS={short:{label:'2–3 hours',hours:3},medium:{label:'4–5 hours',hours:5},long:{label:'6+ hours',hours:7}};
export const FOOD_TYPES={snacks:'Snacks only',pizza:'Pizza / easy food',meal:'Full meal',bbq:'BBQ',finger:'Finger food / buffet',dessert:'Dessert / cake only',separate:'Food handled separately'};
export const DRINK_TYPES={water:'Water',soft:'Soft drinks',beer:'Beer',wine:'Wine',cocktails:'Cocktails / spirits'};
export const VENUES={home:'Home / apartment',garden:'Garden / backyard',park:'Park / outdoors',rented:'Rented venue'};
export const DEFAULT_CONFIG={guests:24,kids:0,party:'birthday',duration:'medium',food:'pizza',drinks:['water','soft'],venue:'home',cake:false,decorations:false,disposable:true};
export const DEFINITIONS=[
['pizza','Large pizzas','Food'],['snacks','Crisps & savoury snacks','Food'],['dips','Dips','Food'],['meal','Main-meal portions','Food'],['sides','Side-dish portions','Food'],['bbq-main','BBQ mains','Food'],['bbq-veg','Vegetarian BBQ portions','Food'],['buns','Burger / hot-dog buns','Food'],['finger','Finger-food pieces','Food'],['dessert','Dessert portions','Food'],['cake','Celebration cake','Cake / celebration'],['candles','Cake candles','Cake / celebration'],['lighter','Lighter or matches','Don’t forget these'],['cake-knife','Cake knife / server','Don’t forget these'],
['water','Drinking water','Drinks'],['soft','Soft drinks','Drinks'],['beer','Beer','Drinks'],['wine','Wine','Drinks'],['spirits','Spirits','Drinks'],['mixers','Cocktail mixers','Drinks'],['garnish','Cocktail garnish','Drinks'],['serving-ice','Ice for serving','Ice'],['chilling-ice','Ice for chilling','Ice'],
['cups','Cups','Tableware'],['plates','Plates','Tableware'],['bowls','Bowls','Tableware'],['napkins','Napkins','Tableware'],['cutlery','Cutlery sets','Tableware'],['serving-trays','Serving trays / platters','Serving'],['serving-tools','Serving spoons / tongs','Serving'],['bottle-opener','Bottle opener','Don’t forget these'],['corkscrew','Corkscrew','Don’t forget these'],['marker','Marker for cups','Don’t forget these'],
['bin-bags','Rubbish bags','Waste & recycling'],['recycling','Recycling bags / boxes','Waste & recycling'],['kitchen-roll','Kitchen roll','Cleaning'],['cleaner','Surface cleaner','Cleaning'],['sponges','Sponges / cloths','Cleaning'],['dishwasher','Dishwasher supplies','Cleaning'],['stain','Stain remover','Don’t forget these'],['toilet-paper','Toilet paper','Bathroom'],['soap','Hand soap','Bathroom'],['hand-towels','Hand towels / paper towels','Bathroom'],
['containers','Leftover containers','Storage & leftovers'],['foil','Foil / food wrap','Storage & leftovers'],['zip-bags','Resealable bags','Storage & leftovers'],['takeaway','Takeaway containers','Storage & leftovers'],
['decor','Decoration set','Decorations'],['tape','Removable tape / hooks','Decorations'],['coolers','Coolers / ice chests','Outdoor essentials'],['blankets','Picnic blankets','Outdoor essentials'],['sun','Sunscreen','Outdoor essentials'],['bug','Insect repellent','Outdoor essentials'],['lighting','Outdoor lights / lanterns','Outdoor essentials'],['extension','Outdoor-rated extension lead','Outdoor essentials'],['bbq-fuel','BBQ fuel','Outdoor essentials'],['table-cover','Table covers','Hosting'],['chairs','Extra seating check','Hosting'],['coat-space','Coat-storage area','Hosting'],['first-aid','Basic first-aid kit','Don’t forget these'],['charger','Spare phone charger','Don’t forget these'],['batteries','Spare batteries','Don’t forget these'],['allergies','Allergy & dietary labels','Don’t forget these'],['condiments','Condiments','Food'],['bread','Bread / rolls','Food']
].map(([id,name,category])=>({id,name,category}));
export const DEF=Object.fromEntries(DEFINITIONS.map(x=>[x.id,x]));
