import{DEFAULT_CONFIG,DEF,PARTY_TYPES,DURATIONS,FOOD_TYPES,DRINK_TYPES,VENUES}from'./data.js';
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));const ceil=(n,step=1)=>Math.ceil(n/step)*step;const range=(low,high,unit)=>({low:ceil(low),high:ceil(high),unit});
export function normalizeConfig(raw={}){const c={...DEFAULT_CONFIG,...raw};c.guests=clamp(Number.isFinite(+c.guests)?Math.round(+c.guests):DEFAULT_CONFIG.guests,2,300);c.kids=clamp(Number.isFinite(+c.kids)?Math.round(+c.kids):0,0,c.guests);for(const[k,map]of[['party',PARTY_TYPES],['duration',DURATIONS],['food',FOOD_TYPES],['venue',VENUES]])if(!map[c[k]])c[k]=DEFAULT_CONFIG[k];c.drinks=[...new Set(Array.isArray(c.drinks)?c.drinks:[])].filter(x=>DRINK_TYPES[x]);if(!c.drinks.length)c.drinks=['water'];for(const k of['cake','decorations','disposable'])c[k]=c[k]===true||c[k]==='true';return c}
function format(q){if(q.text)return q.text;const n=x=>Number.isInteger(x)?String(x):x.toFixed(1).replace(/\.0$/,'');return q.low===q.high?`${n(q.low)} ${q.unit}`:`${n(q.low)}–${n(q.high)} ${q.unit}`}
export function makePlan(input){const c=normalizeConfig(input),g=c.guests,k=c.kids,a=g-k,h=DURATIONS[c.duration].hours,long=h>=6,out=['garden','park'].includes(c.venue),items=[];const add=(id,q,note)=>{if(!q||('low'in q&&q.high<=0))return;items.push({...DEF[id],quantity:format(q),value:q,note})};
 if(c.food==='pizza'){const slices=a*2.6+k*2.1;add('pizza',range(slices/10*0.95,slices/8*1.08,'large'),`Assumes roughly 2–3 slices each, with a small buffer.`);add('snacks',range(g*.06,g*.09,'kg'),'A light pre-food buffer.');add('dips',range(g/12,g/8,'tubs'))}
 if(c.food==='snacks'){add('snacks',range(g*.16*(1+h/12),g*.22*(1+h/12),'kg'),'More for a longer, snacks-only party.');add('dips',range(g/8,g/6,'tubs'))}
 if(c.food==='meal'){add('meal',range(g*1.05,g*1.12,'portions'),'Includes a modest hosting buffer.');add('sides',range(g*1.5,g*2,'portions'));add('bread',range(g*.08,g*.12,'kg'));add('condiments',{text:'3–5 varieties'})}
 if(c.food==='bbq'){add('bbq-main',range(a*1.7+k*1.2,a*2.1+k*1.5,'pieces'),'A mix of grill items; confirm dietary needs.');add('bbq-veg',range(g*.18,g*.25,'portions'),'Keep vegetarian food separate on the grill.');add('buns',range(g*1.2,g*1.6,'pieces'));add('sides',range(g*1.5,g*2,'portions'));add('condiments',{text:'4–6 bottles'})}
 if(c.food==='finger'){const p=h>=6?12:h>=4?10:8;add('finger',range(g*p,g*(p+3),'pieces'),`${p}–${p+3} pieces per guest when finger food is the main food.`);add('dips',range(g/10,g/7,'tubs'))}
 if(c.food==='dessert'){add('dessert',range(g*1.05,g*1.15,'portions'))}
 if(c.cake){add('cake',{text:`1 cake for ${ceil(g*1.1)} servings`},'Allows a small cutting buffer.');add('candles',{text:c.party==='birthday'||c.party==='kids'?'1 pack':'1 optional pack'});add('cake-knife',{text:'1'});add('lighter',{text:'1'})}
 const drinkSlots=g*(h<=3?2.2:h<=5?3.2:4.2),selected=c.drinks,alcohol=selected.filter(x=>['beer','wine','cocktails'].includes(x)),nonAlcohol=selected.filter(x=>['water','soft'].includes(x));if(selected.includes('water')){const litres=g*(h<=3?0.65:h<=5?0.82:1);add('water',range(litres*.9,litres*1.15,'L'),'More in warm weather or outdoors.');}if(selected.includes('soft')){const share=nonAlcohol.length===1&&!alcohol.length?0.8:alcohol.length?0.3:0.55;add('soft',range(drinkSlots*share*.25,drinkSlots*share*.33,'L'),'Includes alcohol-free choice and mixer-friendly variety.')}if(alcohol.length){const adultSlots=a*(h<=3?1.8:h<=5?2.6:3.4),each=adultSlots/alcohol.length;if(selected.includes('beer'))add('beer',range(each*.8,each*1.05,'cans / bottles'),'A purchasing range, not a consumption target.');if(selected.includes('wine'))add('wine',range(each/5*.85,each/5*1.05,'750 ml bottles'),'About five small servings per bottle; unopened bottles may remain.');if(selected.includes('cocktails')){add('spirits',range(each/16*.75,each/16,'700 ml bottles'),'Plan measured serves and plenty of alcohol-free choices.');add('mixers',range(each*.16,each*.24,'L'));add('garnish',{text:g<30?'2–3 packs':'4–6 packs'})}}
 if(selected.length){add('serving-ice',range(g*(out?.25:.18),g*(out?.4:.3),'kg'),'For serving drinks; buy nearer the high end in hot weather.');if(alcohol.length||out)add('chilling-ice',range(g*(out?.35:.22),g*(out?.55:.4),'kg'),'Separate ice for coolers and chilling bottles or cans.')}
 const tableUse=c.food!=='separate'||c.cake;if(c.disposable){add('cups',range(g*(h>=6?2.5:2),g*(h>=6?3:2.5),'pieces'),'Extra cups cover changes and lost cups.');if(tableUse)add('plates',range(g*(c.food==='meal'?1.3:1.1),g*(c.food==='meal'?1.6:1.35),'pieces'));if(['meal','bbq','finger'].includes(c.food))add('cutlery',range(g*1.1,g*1.3,'sets'));}if(tableUse)add('napkins',range(g*(c.food==='bbq'?4:3),g*(c.food==='bbq'?6:4),'pieces'));if(['snacks','finger','meal','bbq','pizza'].includes(c.food)){add('serving-trays',range(Math.max(2,g/12),Math.max(3,g/8),'pieces'));add('serving-tools',range(Math.max(2,g/15),Math.max(3,g/10),'pieces'))}
 if(c.decorations){add('decor',{text:g<40?'1 coordinated set':`${ceil(g/50)} coordinated sets / zones`});add('tape',{text:g<80?'1–2 packs':`${ceil(g/80)}–${ceil(g/50)} packs`})}add('bin-bags',range(Math.max(3,g/10*(1+h/8)),Math.max(5,g/7*(1+h/8)),'bags'));add('recycling',range(Math.max(2,g/15),Math.max(3,g/10),'bags / boxes'));add('kitchen-roll',range(Math.max(1,g/30),Math.max(2,g/20),'rolls'));add('cleaner',{text:g<60?'1 bottle':`${ceil(g/80)}–${ceil(g/50)} bottles`});add('sponges',{text:g<60?'2–3':`${ceil(g/30)}–${ceil(g/20)} cloths / sponges`});if(c.venue==='home')add('dishwasher',{text:g<30?'1 full load supply':`${ceil(g/15)}–${ceil(g/10)} load supply`});add('toilet-paper',range(Math.max(2,g/12*(1+h/10)),Math.max(3,g/8*(1+h/10)),'rolls'));add('soap',{text:`${Math.max(1,ceil(g/75))} full dispenser${g>75?'s':''}`});if(g>=30)add('hand-towels',range(g/15,g/10,'pieces / rolls'));
 if(c.food!=='separate'){add('containers',range(Math.max(3,g/10),Math.max(5,g/6),'pieces'));add('foil',{text:g<40?'1 roll':'2 rolls'});add('zip-bags',{text:g<40?'1 pack':'2 packs'});if(g>=30)add('takeaway',range(g/8,g/5,'pieces'))}
 if(out){add('coolers',range(Math.max(1,g/25),Math.max(2,g/15),'units'));if(c.venue==='park')add('blankets',range(g/6,g/4,'blankets'));add('sun',{text:g<30?'1 bottle':`${ceil(g/35)}–${ceil(g/25)} bottles`});add('bug',{text:g<30?'1 bottle':`${ceil(g/50)}–${ceil(g/35)} bottles`});if(long||c.duration==='medium')add('lighting',{text:g<30?'2–3 units':`${ceil(g/12)}–${ceil(g/8)} units`});if(c.venue==='garden')add('extension',{text:'1, if power is needed'})}if(c.venue==='rented'){add('table-cover',range(g/12,g/8,'covers'));add('chairs',{text:`confirm ${g} seats`})}if(c.venue==='home')add('coat-space',{text:g<20?'1 clear area':`${ceil(g/10)} m rail / equivalent`});
 if(alcohol.includes('beer')||selected.includes('soft'))add('bottle-opener',{text:g>=60?'2':'1'});if(alcohol.includes('wine'))add('corkscrew',{text:g>=50?'2':'1'});if(c.disposable)add('marker',{text:'1–2'});add('first-aid',{text:'1 kit'});if(g>=20)add('charger',{text:'1 multi-cable charger'});if(c.party==='game'||c.party==='watch')add('batteries',{text:'1 spare pack'});add('allergies',{text:'labels + marker'},'Ask guests about allergies and dietary requirements before shopping.');if(c.food==='bbq'&&c.venue!=='rented')add('lighter',{text:'1'});if(c.food==='bbq')add('bbq-fuel',{text:'Enough for one full cook + 20% reserve'});
 const seen=new Set();const unique=items.filter(x=>!seen.has(x.id)&&seen.add(x.id));return{config:c,items:unique,groups:unique.reduce((m,x)=>(m[x.category]??=[]).push(x)&&m,{})}}
export function configKey(config){const c=normalizeConfig(config);return btoa(unescape(encodeURIComponent(JSON.stringify(c)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','').slice(0,180)}
