import{readFile,writeFile,mkdir}from'node:fs/promises';import{dirname,join}from'node:path';import{fileURLToPath}from'node:url';
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),raw=join(root,'data-source','transport-canada-2021.csv');
const text=(await readFile(raw,'utf8')).replace(/^\uFEFF/,'');
const lines=text.trim().split(/\r?\n/);const header=lines.shift().split(',').map(x=>x.trim());
const ix=Object.fromEntries(header.map((x,i)=>[x,i]));const num=x=>/^\d+(?:\.\d+)?$/.test(x)?Number(x):null;
const preferred=['VOLKSWAGEN','TESLA','AUDI','BMW','MERCEDES-BENZ','TOYOTA','HONDA','HYUNDAI','KIA','FORD','MAZDA','NISSAN','VOLVO','SUBARU','LEXUS','PORSCHE','JEEP','CHEVROLET','LAND ROVER','MINI','ACURA','CADILLAC','GENESIS','INFINITI'];
const aliases={'VOLKSWAGEN':['vw'],'MERCEDES-BENZ':['mercedes','benz'],'LAND ROVER':['range rover']};
function body(s){s=s.toUpperCase();if(/PICKUP|F-150|TUNDRA|FRONTIER|TACOMA|RIDGELINE/.test(s))return'pickup';if(/MINIVAN|VAN|CARNIVAL|SIENNA|ODYSSEY|PACIFICA/.test(s))return'mpv';if(/SUV|CROSSOVER/.test(s))return'suv';if(/WAGON|AVANT|TOURING/.test(s))return'wagon';if(/COUPE|2DR|ROADSTER|CONVERTIBLE/.test(s))return'coupe';if(/HATCH|GOLF|LEAF|BOLT/.test(s))return'hatchback';return'sedan'}
function pretty(s){return s.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()).replace(/\bAwd\b/g,'AWD').replace(/\bFwd\b/g,'FWD').replace(/\bSuv\b/g,'SUV').replace(/\bEv\b/g,'EV').replace(/\bDr\b/g,'dr').replace(/\bId\./g,'ID.').replace(/\bIx\b/g,'iX')}
const parsed=lines.map((line,index)=>{const c=line.split(',');const year=num(c[ix.MYR]);return{sourceRow:index+2,make:c[ix.MAKE]?.trim(),rawModel:c[ix.MODEL]?.trim(),year:year==null?null:(year<50?2000+year:1900+year),length:num(c[ix.OL]),width:num(c[ix.OW]),height:num(c[ix.OH]),wheelbase:num(c[ix.WB])}});
const rejected=[];const valid=[];for(const r of parsed){let reason='';if(!r.make||!r.rawModel)reason='missing identity';else if([r.length,r.width,r.height,r.wheelbase].some(x=>x==null))reason='missing required dimension';else if(r.length<250||r.length>700||r.width<130||r.width>240||r.height<100||r.height>300||r.wheelbase<180||r.wheelbase>=r.length)reason='implausible or contradictory dimension';if(reason)rejected.push({...r,reason});else valid.push(r)}
const seen=new Set;const dedup=[];for(const r of valid.sort((a,b)=>(preferred.indexOf(a.make)<0?99:preferred.indexOf(a.make))-(preferred.indexOf(b.make)<0?99:preferred.indexOf(b.make))||b.year-a.year)){const family=r.rawModel.replace(/\b(?:AWD|FWD|RWD|4WD|2WD|QUATTRO|4MOTION|HYBRID|PHEV|EV|[2345]DR|SEDAN|HATCH(?:BACK)?|SUV|COUPE|WAGON|ROADSTER)\b/gi,'').replace(/\s+/g,' ').trim();const key=[r.make,family,r.year,r.length,r.width,r.height,r.wheelbase].join('|');if(seen.has(key)){rejected.push({...r,reason:'duplicate dimensional variant'});continue}seen.add(key);dedup.push({...r,family})}
const must=['TESLA|MODEL Y','TESLA|MODEL 3','VOLKSWAGEN|GOLF ','VOLKSWAGEN|TIGUAN','AUDI|Q5 ','BMW|X3 ','TOYOTA|RAV4','HONDA|CR-V'];
const chosen=[];const makeCounts=new Map;for(const needle of must){const [m,q]=needle.split('|'),r=dedup.find(x=>x.make===m&&x.rawModel.includes(q.trim()));if(r&&!chosen.includes(r)){chosen.push(r);makeCounts.set(m,(makeCounts.get(m)||0)+1)}}for(let cap=10;chosen.length<240&&cap<=30;cap+=5){for(const r of dedup){if(chosen.length>=240)break;if(chosen.includes(r)||(makeCounts.get(r.make)||0)>=cap)continue;chosen.push(r);makeCounts.set(r.make,(makeCounts.get(r.make)||0)+1)}}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
const ids=new Set;const vehicles=chosen.map(r=>{let id=slug(`${r.make}-${r.family}-${r.year}`),n=2,base=id;while(ids.has(id))id=`${base}-${n++}`;ids.add(id);return{id,make:pretty(r.make),model:pretty(r.rawModel),generation:`${r.year} Canadian specification`,year_start:r.year,year_end:r.year,body_type:body(r.rawModel),market:'Canada',length_mm:r.length*10,width_mm:r.width*10,height_mm:r.height*10,wheelbase_mm:r.wheelbase*10,width_semantics:'overall body width; mirrors excluded',aliases:aliases[r.make]||[],source:{dataset:'Transport Canada Canadian Vehicle Specifications',snapshot:'2021 English CSV',row:r.sourceRow,license:'Open Government Licence – Canada'}}});
const counts=Object.fromEntries([...new Set(vehicles.map(v=>v.body_type))].sort().map(k=>[k,vehicles.filter(v=>v.body_type===k).length]));
const report={generated:'2026-09-22',primary_source:'Transport Canada — Canadian Vehicle Specifications (CVS)',source_url:'https://open.canada.ca/data/en/dataset/913f8940-036a-45f2-a5f2-19bde76c1252',license:'Open Government Licence – Canada',attribution:'Contains information licensed under the Open Government Licence – Canada.',snapshot:'2021 English CSV',original_records:parsed.length,complete_plausible_records:valid.length,usable_curated_records:vehicles.length,rejected_total:rejected.length,rejection_reasons:Object.fromEntries([...new Set(rejected.map(r=>r.reason))].map(k=>[k,rejected.filter(r=>r.reason===k).length])),not_selected_after_balanced_curation:dedup.length-vehicles.length,makes:[...new Set(vehicles.map(v=>v.make))].sort(),body_type_distribution:counts,width_semantics:'OW is Overall Width in centimetres. Catalog records were retained only where values are consistent with body width excluding mirrors; mirror width is not present.',ambiguous_width_records:0,missing_dimension_records:rejected.filter(r=>r.reason==='missing required dimension').length,duplicate_generation_records:rejected.filter(r=>r.reason==='duplicate dimensional variant').length,suspicious_outliers:[{source_row:841,record:'MERCEDES-BENZ EQS CLASS EV 4DR SEDAN',issue:'OW=293 cm, rejected as implausible'},{source_row:980,record:'VOLKSWAGEN ATLAS CROSS SPORT',issue:'curb-weight anomaly is outside fields shipped and was not imported'}],manually_verified:['Volkswagen Golf 4DR Hatch (2015 geometry)','Tesla Model Y 4DR SUV AWD (2021 geometry)','Tesla Model 3 Long Range AWD (2018 geometry)','Audi Q5 4DR SUV (2021 geometry)','Toyota RAV4 AWD (2019 geometry)','Honda CR-V AWD (2017 geometry)'],secondary_sources:['AutoSeeker Open Car Data (license and coverage evaluation; not imported because wheelbase is absent)','Transport Canada CVS data dictionary (field semantics)']};
await mkdir(join(root,'src','data'),{recursive:true});await writeFile(join(root,'src','data','vehicles.json'),JSON.stringify({meta:{source:report.primary_source,license:report.license,count:vehicles.length,width_semantics:report.width_semantics},vehicles},null,2)+'\n');await writeFile(join(root,'data-source','provenance-report.json'),JSON.stringify(report,null,2)+'\n');console.log(`Imported ${vehicles.length} vehicles from ${parsed.length} source rows; ${rejected.length} rows rejected or deduplicated.`)
