export const MOODS = ['funny', 'scary', 'exciting', 'chill', 'serious'];

// Runtime is the standard theatrical runtime in minutes. Tags are editorial,
// intentionally broad mood signals rather than ratings or plot summaries.
export const movies = [
  ['12-angry-men','12 Angry Men',1957,96,['serious'],['Drama']],
  ['2001-a-space-odyssey','2001: A Space Odyssey',1968,149,['chill','serious'],['Science fiction']],
  ['a-quiet-place','A Quiet Place',2018,90,['scary','serious'],['Horror','Thriller']],
  ['after-hours','After Hours',1985,97,['funny','exciting'],['Comedy','Thriller']],
  ['airplane','Airplane!',1980,88,['funny'],['Comedy']],
  ['alien','Alien',1979,117,['scary','serious'],['Horror','Science fiction']],
  ['aliens','Aliens',1986,137,['scary','exciting'],['Action','Science fiction']],
  ['all-about-eve','All About Eve',1950,138,['serious'],['Drama']],
  ['almost-famous','Almost Famous',2000,122,['funny','chill'],['Comedy','Drama']],
  ['amelie','Amélie',2001,122,['funny','chill'],['Comedy','Romance']],
  ['an-american-werewolf-in-london','An American Werewolf in London',1981,97,['funny','scary'],['Comedy','Horror']],
  ['anatomy-of-a-fall','Anatomy of a Fall',2023,152,['serious'],['Drama','Mystery']],
  ['arrival','Arrival',2016,116,['chill','serious'],['Drama','Science fiction']],
  ['attack-the-block','Attack the Block',2011,88,['funny','exciting'],['Action','Science fiction']],
  ['babe','Babe',1995,91,['funny','chill'],['Comedy','Family']],
  ['back-to-the-future','Back to the Future',1985,116,['funny','exciting'],['Adventure','Comedy']],
  ['before-sunrise','Before Sunrise',1995,101,['chill','serious'],['Drama','Romance']],
  ['being-john-malkovich','Being John Malkovich',1999,113,['funny','serious'],['Comedy','Fantasy']],
  ['best-in-show','Best in Show',2000,90,['funny','chill'],['Comedy']],
  ['big-trouble-in-little-china','Big Trouble in Little China',1986,99,['funny','exciting'],['Action','Comedy']],
  ['black-dynamite','Black Dynamite',2009,84,['funny','exciting'],['Action','Comedy']],
  ['blade-runner','Blade Runner',1982,117,['chill','serious'],['Science fiction','Thriller']],
  ['bottoms','Bottoms',2023,91,['funny','exciting'],['Comedy']],
  ['brick','Brick',2005,110,['serious'],['Crime','Mystery']],
  ['bringing-up-baby','Bringing Up Baby',1938,102,['funny'],['Comedy','Romance']],
  ['burn-after-reading','Burn After Reading',2008,96,['funny'],['Comedy','Crime']],
  ['casablanca','Casablanca',1942,102,['chill','serious'],['Drama','Romance']],
  ['chef','Chef',2014,114,['funny','chill'],['Comedy','Drama']],
  ['children-of-men','Children of Men',2006,109,['exciting','serious'],['Drama','Science fiction']],
  ['clueless','Clueless',1995,97,['funny','chill'],['Comedy','Romance']],
  ['coherence','Coherence',2013,89,['scary','serious'],['Mystery','Science fiction']],
  ['collateral','Collateral',2004,120,['exciting','serious'],['Crime','Thriller']],
  ['coraline','Coraline',2009,100,['scary','exciting'],['Animation','Fantasy']],
  ['do-the-right-thing','Do the Right Thing',1989,120,['serious'],['Comedy','Drama']],
  ['dog-day-afternoon','Dog Day Afternoon',1975,125,['exciting','serious'],['Crime','Drama']],
  ['drive','Drive',2011,100,['exciting','serious'],['Crime','Drama']],
  ['dune-part-two','Dune: Part Two',2024,166,['exciting','serious'],['Adventure','Science fiction']],
  ['edge-of-tomorrow','Edge of Tomorrow',2014,113,['funny','exciting'],['Action','Science fiction']],
  ['evil-dead-ii','Evil Dead II',1987,84,['funny','scary'],['Comedy','Horror']],
  ['fantastic-mr-fox','Fantastic Mr. Fox',2009,87,['funny','chill'],['Animation','Comedy']],
  ['fargo','Fargo',1996,98,['funny','serious'],['Crime','Drama']],
  ['first-reformed','First Reformed',2017,113,['serious'],['Drama']],
  ['frances-ha','Frances Ha',2012,86,['funny','chill'],['Comedy','Drama']],
  ['galaxy-quest','Galaxy Quest',1999,102,['funny','exciting'],['Comedy','Science fiction']],
  ['get-out','Get Out',2017,104,['scary','serious'],['Horror','Mystery']],
  ['ghostbusters','Ghostbusters',1984,105,['funny','exciting'],['Comedy','Fantasy']],
  ['good-time','Good Time',2017,102,['exciting','serious'],['Crime','Thriller']],
  ['groundhog-day','Groundhog Day',1993,101,['funny','chill'],['Comedy','Fantasy']],
  ['halloween','Halloween',1978,91,['scary'],['Horror','Thriller']],
  ['harold-and-maude','Harold and Maude',1971,91,['funny','chill'],['Comedy','Drama']],
  ['heat','Heat',1995,170,['exciting','serious'],['Crime','Drama']],
  ['hell-or-high-water','Hell or High Water',2016,102,['exciting','serious'],['Crime','Drama']],
  ['her','Her',2013,126,['chill','serious'],['Drama','Romance']],
  ['his-girl-friday','His Girl Friday',1940,92,['funny'],['Comedy','Romance']],
  ['hot-fuzz','Hot Fuzz',2007,121,['funny','exciting'],['Action','Comedy']],
  ['hunt-for-the-wilderpeople','Hunt for the Wilderpeople',2016,101,['funny','chill'],['Adventure','Comedy']],
  ['in-the-mood-for-love','In the Mood for Love',2000,98,['chill','serious'],['Drama','Romance']],
  ['inside-man','Inside Man',2006,129,['exciting','serious'],['Crime','Thriller']],
  ['it-follows','It Follows',2014,100,['scary','serious'],['Horror','Mystery']],
  ['jaws','Jaws',1975,124,['scary','exciting'],['Adventure','Thriller']],
  ['jurassic-park','Jurassic Park',1993,127,['exciting'],['Adventure','Science fiction']],
  ['kikis-delivery-service','Kiki’s Delivery Service',1989,103,['chill'],['Animation','Fantasy']],
  ['knives-out','Knives Out',2019,130,['funny','exciting'],['Comedy','Mystery']],
  ['la-haine','La Haine',1995,98,['serious'],['Crime','Drama']],
  ['lady-bird','Lady Bird',2017,94,['funny','serious'],['Comedy','Drama']],
  ['little-miss-sunshine','Little Miss Sunshine',2006,101,['funny','chill'],['Comedy','Drama']],
  ['logan-lucky','Logan Lucky',2017,118,['funny','exciting'],['Comedy','Crime']],
  ['lost-in-translation','Lost in Translation',2003,102,['chill','serious'],['Comedy','Drama']],
  ['mad-max-fury-road','Mad Max: Fury Road',2015,120,['exciting'],['Action','Science fiction']],
  ['marcel-the-shell-with-shoes-on','Marcel the Shell with Shoes On',2021,90,['funny','chill'],['Animation','Comedy']],
  ['memento','Memento',2000,113,['exciting','serious'],['Mystery','Thriller']],
  ['midnight-run','Midnight Run',1988,126,['funny','exciting'],['Action','Comedy']],
  ['minari','Minari',2020,115,['chill','serious'],['Drama']],
  ['moon','Moon',2009,97,['chill','serious'],['Drama','Science fiction']],
  ['moonlight','Moonlight',2016,111,['chill','serious'],['Drama']],
  ['moonrise-kingdom','Moonrise Kingdom',2012,94,['funny','chill'],['Comedy','Drama']],
  ['my-neighbor-totoro','My Neighbor Totoro',1988,86,['chill'],['Animation','Fantasy']],
  ['network','Network',1976,121,['funny','serious'],['Drama']],
  ['nightcrawler','Nightcrawler',2014,117,['scary','serious'],['Crime','Thriller']],
  ['no-country-for-old-men','No Country for Old Men',2007,122,['scary','serious'],['Crime','Drama']],
  ['nope','Nope',2022,130,['scary','exciting'],['Horror','Science fiction']],
  ['oceans-eleven','Ocean’s Eleven',2001,116,['funny','chill'],['Comedy','Crime']],
  ['one-cut-of-the-dead','One Cut of the Dead',2017,96,['funny','scary'],['Comedy','Horror']],
  ['paddington-2','Paddington 2',2017,103,['funny','chill'],['Comedy','Family']],
  ['palm-springs','Palm Springs',2020,90,['funny','chill'],['Comedy','Romance']],
  ['parasite','Parasite',2019,132,['exciting','serious'],['Drama','Thriller']],
  ['perfect-blue','Perfect Blue',1997,81,['scary','serious'],['Animation','Thriller']],
  ['petite-maman','Petite Maman',2021,72,['chill','serious'],['Drama','Fantasy']],
  ['point-break','Point Break',1991,122,['exciting'],['Action','Crime']],
  ['police-story','Police Story',1985,100,['funny','exciting'],['Action','Comedy']],
  ['porco-rosso','Porco Rosso',1992,94,['funny','chill'],['Animation','Adventure']],
  ['prisoners','Prisoners',2013,153,['scary','serious'],['Crime','Thriller']],
  ['psycho','Psycho',1960,109,['scary','serious'],['Horror','Thriller']],
  ['punch-drunk-love','Punch-Drunk Love',2002,95,['funny','serious'],['Comedy','Romance']],
  ['raging-bull','Raging Bull',1980,129,['serious'],['Drama']],
  ['raiders-of-the-lost-ark','Raiders of the Lost Ark',1981,115,['funny','exciting'],['Action','Adventure']],
  ['rear-window','Rear Window',1954,112,['exciting','serious'],['Mystery','Thriller']],
  ['rec','REC',2007,78,['scary','exciting'],['Horror','Thriller']],
  ['robot-dreams','Robot Dreams',2023,102,['chill','serious'],['Animation','Drama']],
  ['rocky','Rocky',1976,120,['exciting','serious'],['Drama']],
  ['rope','Rope',1948,80,['exciting','serious'],['Crime','Thriller']],
  ['rushmore','Rushmore',1998,93,['funny','chill'],['Comedy','Drama']],
  ['school-of-rock','School of Rock',2003,109,['funny','chill'],['Comedy']],
  ['scream','Scream',1996,111,['funny','scary'],['Horror','Mystery']],
  ['searching','Searching',2018,102,['exciting','serious'],['Mystery','Thriller']],
  ['shaun-of-the-dead','Shaun of the Dead',2004,99,['funny','scary'],['Comedy','Horror']],
  ['sing-street','Sing Street',2016,106,['funny','chill'],['Comedy','Drama']],
  ['singin-in-the-rain','Singin’ in the Rain',1952,103,['funny','chill'],['Comedy','Musical']],
  ['snowpiercer','Snowpiercer',2013,126,['exciting','serious'],['Action','Science fiction']],
  ['some-like-it-hot','Some Like It Hot',1959,121,['funny'],['Comedy','Romance']],
  ['sorcerer','Sorcerer',1977,121,['exciting','serious'],['Adventure','Thriller']],
  ['spirited-away','Spirited Away',2001,125,['chill','exciting'],['Animation','Fantasy']],
  ['stand-by-me','Stand by Me',1986,89,['chill','serious'],['Adventure','Drama']],
  ['stop-making-sense','Stop Making Sense',1984,88,['exciting','chill'],['Documentary','Music']],
  ['superbad','Superbad',2007,113,['funny'],['Comedy']],
  ['talk-to-me','Talk to Me',2022,95,['scary','exciting'],['Horror','Thriller']],
  ['tampopo','Tampopo',1985,114,['funny','chill'],['Comedy']],
  ['the-apartment','The Apartment',1960,125,['funny','chill'],['Comedy','Drama']],
  ['the-babadook','The Babadook',2014,94,['scary','serious'],['Drama','Horror']],
  ['the-big-lebowski','The Big Lebowski',1998,117,['funny','chill'],['Comedy','Crime']],
  ['the-birds','The Birds',1963,119,['scary','serious'],['Horror','Thriller']],
  ['the-cabin-in-the-woods','The Cabin in the Woods',2011,95,['funny','scary'],['Comedy','Horror']],
  ['the-farewell','The Farewell',2019,100,['funny','serious'],['Comedy','Drama']],
  ['the-fugitive','The Fugitive',1993,130,['exciting','serious'],['Action','Thriller']],
  ['the-grand-budapest-hotel','The Grand Budapest Hotel',2014,99,['funny','chill'],['Adventure','Comedy']],
  ['the-iron-giant','The Iron Giant',1999,86,['chill','serious'],['Animation','Science fiction']],
  ['the-lighthouse','The Lighthouse',2019,109,['scary','serious'],['Drama','Fantasy']],
  ['the-lives-of-others','The Lives of Others',2006,137,['serious'],['Drama','Thriller']],
  ['the-matrix','The Matrix',1999,136,['exciting','serious'],['Action','Science fiction']],
  ['the-nice-guys','The Nice Guys',2016,116,['funny','exciting'],['Comedy','Crime']],
  ['the-princess-bride','The Princess Bride',1987,98,['funny','chill'],['Adventure','Comedy']],
  ['the-raid','The Raid',2011,101,['exciting'],['Action','Thriller']],
  ['the-social-network','The Social Network',2010,120,['exciting','serious'],['Drama']],
  ['the-thing','The Thing',1982,109,['scary','serious'],['Horror','Science fiction']],
  ['the-truman-show','The Truman Show',1998,103,['funny','serious'],['Comedy','Drama']],
  ['the-wailing','The Wailing',2016,156,['scary','serious'],['Horror','Mystery']],
  ['the-witch','The Witch',2015,92,['scary','serious'],['Drama','Horror']],
  ['this-is-spinal-tap','This Is Spinal Tap',1984,82,['funny'],['Comedy','Music']],
  ['three-colours-red','Three Colours: Red',1994,99,['chill','serious'],['Drama','Mystery']],
  ['train-to-busan','Train to Busan',2016,118,['scary','exciting'],['Action','Horror']],
  ['tremors','Tremors',1990,96,['funny','exciting'],['Comedy','Horror']],
  ['unbreakable','Unbreakable',2000,106,['chill','serious'],['Drama','Thriller']],
  ['upgrade','Upgrade',2018,100,['exciting','serious'],['Action','Science fiction']],
  ['wall-e','WALL·E',2008,98,['chill','serious'],['Animation','Science fiction']],
  ['what-we-do-in-the-shadows','What We Do in the Shadows',2014,86,['funny','chill'],['Comedy','Horror']],
  ['whiplash','Whiplash',2014,106,['exciting','serious'],['Drama','Music']],
  ['wild-tales','Wild Tales',2014,122,['funny','exciting'],['Comedy','Drama']],
  ['wings-of-desire','Wings of Desire',1987,128,['chill','serious'],['Drama','Fantasy']],
  ['wolfwalkers','Wolfwalkers',2020,103,['exciting','chill'],['Animation','Adventure']],
  ['zodiac','Zodiac',2007,157,['serious'],['Crime','Mystery']]
].map(([id, title, year, runtimeMinutes, moods, genres]) => ({ id, title, year, runtimeMinutes, moods, genres }));
