import{puzzles,categories,puzzleById}from'./puzzles.js';import{createSession,pointsFor}from'./game.js';
const $=id=>document.getElementById(id),game=createSession(puzzles);const el={intro:$('intro'),round:$('round'),reveal:$('reveal'),judgement:$('judgement'),result:$('result'),clue:$('clue'),hint:$('hint-count'),answer:$('answer'),descriptor:$('descriptor'),reaction:$('reaction'),detail:$('result-detail'),announcer:$('announcer'),status:$('share-status'),more:$('more'),giveUp:$('give-up'),category:$('category-label'),tray:$('category-tray'),toggle:$('categories-toggle'),options:$('category-options')};
const sharedId=new URL(location.href).searchParams.get('p');const sharedPuzzle=sharedId&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(sharedId)?puzzleById.get(sharedId):null;if(sharedPuzzle){$('challenge-copy').textContent='SOMEONE SENT YOU A MYSTERY.';document.querySelector('.lede').textContent='Can you crack the same puzzle? The answer stays hidden until you choose.'}
function setView(view){el.intro.hidden=view!=='intro';el.round.hidden=view!=='round';el.reveal.hidden=view!=='reveal';document.querySelector('#screen').className=`screen ${view}-screen`}
function updateStats(){const s=game.stats;$('stat-played').textContent=s.played;$('stat-solved').textContent=s.solved;$('stat-score').textContent=s.score;$('stat-average').textContent=s.solved?(s.hintsTotal/s.solved).toFixed(1):'—';$('stat-best').textContent=s.best===null?'—':`${s.best} HINT${s.best===1?'':'S'}`}
function showHint(focus=false){setView('round');el.hint.textContent=`HINT ${game.hint} OF 5`;el.clue.textContent=game.current.hints[game.hint-1];document.querySelectorAll('.clue-meter span').forEach((node,i)=>node.classList.toggle('lit',i<game.hint));el.more.hidden=game.hint===5;el.giveUp.hidden=game.hint!==5;el.announcer.textContent=`Hint ${game.hint} of 5. ${el.clue.textContent}`;if(focus)el.clue.focus()}
function start(puzzle){game.start(puzzle);history.replaceState({},'',`?p=${encodeURIComponent(game.current.id)}`);$('mystery-label').textContent=`MYSTERY #${String(game.current.number).padStart(3,'0')}`;el.category.textContent=game.current.category.toUpperCase();showHint();$('know').focus()}
function reveal(){setView('reveal');el.answer.textContent=game.current.answer;el.descriptor.textContent=game.current.descriptor;el.judgement.hidden=game.intent!=='claim';el.result.hidden=game.intent==='claim';el.announcer.textContent=`The answer was ${game.current.answer}.`;if(game.intent==='claim')$('yes').focus()}
const copyByHint={1:['LIGHTS OUT.','Five points. That was alarmingly quick.'],2:['SHARP WORK.','Four points. You saw it coming.'],3:['SOLID READ.','Three points. Right down the middle.'],4:['JUST IN TIME.','Two points. The board nearly had you.'],5:['WE GOT THERE.','One point. A solve is a solve.']};
function finish(){el.judgement.hidden=true;el.result.hidden=false;let copy;if(game.intent==='solved')copy=copyByHint[game.hint];else if(game.intent==='missed')copy=['BEAUTIFUL MISS.','No points, no shame. The next one is waiting.'];else copy=['HONEST EXIT.','Zero points. Curiosity still wins.'];el.reaction.textContent=copy[0];el.detail.textContent=copy[1];updateStats();$('next').focus()}
$('start').addEventListener('click',()=>start(sharedPuzzle||undefined));$('more').addEventListener('click',()=>{game.nextHint();showHint(true)});$('know').addEventListener('click',()=>{game.know();reveal()});$('give-up').addEventListener('click',()=>{game.giveUp();reveal();finish()});$('yes').addEventListener('click',()=>{game.judge(true);finish()});$('no').addEventListener('click',()=>{game.judge(false);finish()});$('next').addEventListener('click',()=>start());
el.toggle.addEventListener('click',()=>{const open=el.tray.hidden;el.tray.hidden=!open;el.toggle.setAttribute('aria-expanded',String(open));if(open)el.options.querySelector('button')?.focus()});
for(const category of categories){const button=document.createElement('button');button.type='button';button.textContent=category.toUpperCase();button.dataset.category=category;button.setAttribute('aria-pressed',String(category===game.category));button.addEventListener('click',()=>{game.setCategory(category);el.category.textContent=category.toUpperCase();for(const item of el.options.children)item.setAttribute('aria-pressed',String(item===button));el.tray.hidden=true;el.toggle.setAttribute('aria-expanded','false');$('challenge-copy').textContent='WHAT AM I?';document.querySelector('.lede').textContent=`Five clues from strange to obvious. ${category==='Everything'?'How early can you figure it out?':`Category: ${category}.`}`;setView('intro');$('start').focus()});el.options.append(button)}
$('share').addEventListener('click',async()=>{const url=`${location.origin}${location.pathname}?p=${encodeURIComponent(game.current.id)}`,text=game.shareText(url);try{if(navigator.share)await navigator.share({title:'One More Hint',text,url});else{await navigator.clipboard.writeText(text);el.status.textContent='Challenge copied. No answer included.'}}catch(error){if(error?.name!=='AbortError')el.status.textContent='Sharing was unavailable. Copy the page address to challenge a friend.'}});
updateStats();document.body.dataset.ready='true';
