import{createPlan,configFromSearch,searchFromConfig}from'./planner.js';
const $=s=>document.querySelector(s),form=$('#planner'),result=$('#result'),schedule=$('#schedule'),status=$('#status'),money=new Intl.NumberFormat('en',{style:'currency',currency:'EUR',maximumFractionDigits:0}),labels={individual:'Mostly individual',hybrid:'Hybrid / flexible',collaborative:'Collaborative / creative',client:'Client-facing',provided:'Laptops provided',peripherals:'Need peripherals',full:'Full workstations',lean:'Lean',balanced:'Balanced',premium:'Premium'};let plan;
function fill(c){form.people.value=c.people;form.style.value=c.style;form.computer.value=c.computer;form.rooms.value=c.rooms;form.level.value=c.level;form.querySelectorAll('[name=spaces]').forEach(x=>x.checked=c.spaces.includes(x.value));$('#people-output').value=c.people}
function read(){return{people:Number(form.people.value),style:form.style.value,computer:form.computer.value,rooms:Number(form.rooms.value),spaces:[...form.querySelectorAll('[name=spaces]:checked')].map(x=>x.value),level:form.level.value}}
const storageKey=key=>`office-plan:v1:${key}`;function checked(){try{return new Set(JSON.parse(localStorage.getItem(storageKey(plan.key)))||[])}catch{return new Set}}
function save(set){localStorage.setItem(storageKey(plan.key),JSON.stringify([...set]))}
function progress(){const set=checked(),count=plan.categories.flatMap(x=>x.items).filter(x=>set.has(x.id)).length;$('#progress-text').textContent=`${count} of ${plan.itemCount} items sorted`;$('#progress').value=count;$('#progress').max=plan.itemCount}
function assumptions(c){return`${c.people} people · ${labels[c.style]} · ${labels[c.computer]} · ${c.rooms} meeting room${c.rooms===1?'':'s'} · ${labels[c.level]}`}
function render(input,push=true){plan=createPlan(input);if(push)history.replaceState(null,'',searchFromConfig(plan.config));$('#assumptions').textContent=assumptions(plan.config);$('#total').textContent=`${money.format(plan.low)} – ${money.format(plan.high)}`;$('#tier-stamp').textContent=plan.config.level.toUpperCase();schedule.replaceChildren();for(const category of plan.categories){const section=document.createElement('section');section.className='category';const head=document.createElement('header'),title=document.createElement('h3'),sum=document.createElement('strong');title.textContent=category.name;sum.textContent=`${money.format(category.low)} – ${money.format(category.high)}`;head.append(title,sum);section.append(head);for(const item of category.items){const row=document.createElement('label');row.className='item-row';const box=document.createElement('input');box.type='checkbox';box.dataset.id=item.id;box.checked=checked().has(item.id);const body=document.createElement('span');body.className='item-main';const name=document.createElement('b');name.textContent=item.name;const why=document.createElement('small');why.textContent=item.why;body.append(name,why);const qty=document.createElement('strong');qty.className='qty';qty.textContent=`× ${item.quantity}`;const price=document.createElement('span');price.className='price';price.textContent=`${money.format(item.unitLow)}–${money.format(item.unitHigh)} each · ${money.format(item.low)}–${money.format(item.high)}`;row.append(box,body,qty,price);section.append(row)}schedule.append(section)}result.hidden=false;progress();result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#result-title').focus({preventScroll:true});status.textContent='Shopping plan generated.'}
function textPlan(){const lines=['OFFICE SETUP SHOPPING PLAN',assumptions(plan.config),`Planning estimate: ${money.format(plan.low)} – ${money.format(plan.high)}`,''];for(const c of plan.categories){lines.push(c.name.toUpperCase()+` — ${money.format(c.low)}–${money.format(c.high)}`);for(const x of c.items)lines.push(`[ ] ${x.name} × ${x.quantity} — ${money.format(x.unitLow)}–${money.format(x.unitHigh)} each; ${money.format(x.low)}–${money.format(x.high)} — ${x.why}`);lines.push('')}lines.push('Planning estimates, not quotes. Check applicable local workplace, fire, accessibility and electrical requirements.');return lines.join('\n')}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}}
form.addEventListener('input',e=>{if(e.target.name==='people')$('#people-output').value=e.target.value});form.addEventListener('submit',e=>{e.preventDefault();render(read())});schedule.addEventListener('change',e=>{if(e.target.type!=='checkbox')return;const set=checked();e.target.checked?set.add(e.target.dataset.id):set.delete(e.target.dataset.id);save(set);progress()});
$('#copy').addEventListener('click',async()=>{await copyText(textPlan());status.textContent='Shopping list copied.'});$('#print').addEventListener('click',()=>window.print());$('#share').addEventListener('click',async()=>{const url=location.href;try{if(navigator.share)await navigator.share({title:'Office setup shopping plan',text:assumptions(plan.config),url});else{await copyText(url);status.textContent='Plan link copied.'}}catch(error){if(error.name!=='AbortError')status.textContent='Could not share this plan.'}});$('#reset').addEventListener('click',()=>{if(confirm('Reset every checked item in this plan?')){localStorage.removeItem(storageKey(plan.key));schedule.querySelectorAll('input').forEach(x=>x.checked=false);progress();status.textContent='Checklist reset.'}});
document.querySelectorAll('[data-current-year]').forEach(x=>x.textContent=new Date().getFullYear());const initial=configFromSearch(location.search);fill(initial);if(location.search)render(initial,false);
