import{readFile,writeFile}from'node:fs/promises';
const sources=[['athlete','sports'],['comedian','comedy'],['creator','creator'],['rapper','music'],['director2','film-tv'],['presenter2','media']];
const aliases={'dwayne-johnson':['The Rock'],'robert-downey-jr':['RDJ'],'marshall-mathers':['Eminem'],'eminem':['Marshall Mathers'],'sean-combs':['Diddy','Puff Daddy'],'willard-carroll-smith-ii':['Will Smith'],'cristiano-ronaldo':['CR7'],'edson-arantes-do-nascimento':['Pelé']};
const slug=s=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[“”"'.’]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const people=new Map;
for(const[file,category]of[['screen','film-tv'],['music','music']]){const data=JSON.parse(await readFile(`/tmp/spw-seed-${file}.json`,'utf8')).entities;for(const[qid,row]of Object.entries(data)){const value=row.claims?.P569?.[0]?.mainsnak?.datavalue?.value,name=row.sitelinks?.enwiki?.title||row.labels?.en?.value;if(!name||!value||row.claims?.P570)continue;const birthDate=value.time?.match(/[+-](\d{4}-\d{2}-\d{2})/)?.[1],id=slug(name);if(!birthDate||!id)continue;people.set(qid,{id,name,birthDate,category,knownFor:category==='music'?'Music':'Film & television',...(aliases[id]?{aliases:aliases[id]}:{}),source:`https://www.wikidata.org/wiki/${qid}`})}}
for(const[file,category]of sources){const data=JSON.parse(await readFile(`/tmp/spw-${file}.json`,'utf8')).results.bindings;for(const row of data){const name=row.personLabel.value,qid=row.person.value.split('/').pop(),birthDate=row.birth.value.slice(0,10);if(/^Q\d+$/.test(name)||!/^\d{4}-\d{2}-\d{2}$/.test(birthDate))continue;const id=slug(name);if(!id)continue;const existing=people.get(qid);if(existing){if(existing.birthDate!==birthDate)existing.ambiguous=true;continue}people.set(qid,{id,name,birthDate,category,knownFor:{sports:'Sport',comedy:'Comedy',creator:'Online media',music:'Music','film-tv':'Film & television',media:'Television & media'}[category],...(aliases[id]?{aliases:aliases[id]}:{}),source:`https://www.wikidata.org/wiki/${qid}`})}}
let rows=[...people.values()].filter(x=>!x.ambiguous);const ids=new Set;rows=rows.filter(x=>!ids.has(x.id)&&(ids.add(x.id),true)).sort((a,b)=>a.name.localeCompare(b.name));
await writeFile(new URL('../src/js/celebrities.js',import.meta.url),`// Curated from living-person Wikidata records; source URL retained per entry.\nexport const celebrities=${JSON.stringify(rows)};\n`);console.log(`Wrote ${rows.length} people`);
