import test from 'node:test';import assert from 'node:assert/strict';
import{activities,BUDGETS,CATEGORIES}from'../src/js/catalog.js';
import{coverageMatrix,eligibleActivities,findNearDuplicateTitles,nextHistory,normalizeTitle,parseUrlState,pickActivity,shareText,validateActivities}from'../src/js/recommender.js';

test('the full catalog validates and has at least 150 distinct activities',()=>{assert.deepEqual(validateActivities(activities),[]);assert.ok(activities.length>=150);assert.equal(new Set(activities.map(item=>item.id)).size,activities.length);assert.equal(new Set(activities.map(item=>normalizeTitle(item.title))).size,activities.length);assert.deepEqual(findNearDuplicateTitles(activities),[])});
test('every budget and category combination has strong coverage',()=>{const matrix=coverageMatrix(activities);console.log('\nEligibility coverage (category × minutes)');console.log(['Category',...BUDGETS].map(value=>String(value).padStart(8)).join(' '));for(const category of CATEGORIES)console.log([category,...BUDGETS.map(budget=>matrix[category][budget])].map(value=>String(value).padStart(8)).join(' '));for(const category of CATEGORIES)for(const budget of BUDGETS)assert.ok(matrix[category][budget]>=15,`${category} at ${budget} minutes has ${matrix[category][budget]}`)});
for(const budget of BUDGETS)test(`${budget}-minute eligibility respects duration ranges`,()=>{const pool=eligibleActivities(activities,budget);assert.ok(pool.length>=105);assert.ok(pool.every(item=>item.minMinutes<=budget&&item.maxMinutes>=budget))});
for(const category of CATEGORIES)test(`${category} has meaningful catalog depth`,()=>{const items=activities.filter(item=>item.category===category);assert.ok(items.length>=20);assert.ok(items.every(item=>item.category===category))});
test('Anything combines categories',()=>{assert.deepEqual(new Set(eligibleActivities(activities,90).map(item=>item.category)),new Set(CATEGORIES))});
test('duration and category boundaries include valid and exclude invalid activities',()=>{const sample=[{id:'a',category:'move',minMinutes:30,maxMinutes:45},{id:'b',category:'make',minMinutes:46,maxMinutes:90}];assert.deepEqual(eligibleActivities(sample,45).map(x=>x.id),['a']);assert.deepEqual(eligibleActivities(sample,90,'move'),[]);assert.deepEqual(eligibleActivities(sample,90,'make').map(x=>x.id),['b']);assert.deepEqual(eligibleActivities(sample,999),[])});
test('selection avoids repeats until exhaustion and immediate repeat after exhaustion',()=>{const pool=[{id:'a'},{id:'b'},{id:'c'}];assert.equal(pickActivity(pool,[],()=>0).id,'a');assert.equal(pickActivity(pool,['a'],()=>0).id,'b');assert.equal(pickActivity(pool,['a','b'],()=>0).id,'c');assert.notEqual(pickActivity(pool,['a','b','c'],()=>.999).id,'c')});
test('Try Another exhausts each real filtered pool before repeating',()=>{for(const category of ['anything',...CATEGORIES])for(const budget of BUDGETS){const pool=eligibleActivities(activities,budget,category);let history=[];const picked=[];for(let index=0;index<pool.length;index++){const item=pickActivity(pool,history,()=>.37);picked.push(item.id);history=nextHistory(history,item.id,pool.length)}assert.equal(new Set(picked).size,pool.length,`${category} at ${budget} repeated early`);const next=pickActivity(pool,history,()=>.37);assert.notEqual(next.id,picked.at(-1),`${category} at ${budget} repeated immediately after exhaustion`)}});
test('every category and duration filter returns only compatible activities',()=>{for(const category of CATEGORIES)for(const budget of BUDGETS){const pool=eligibleActivities(activities,budget,category);assert.ok(pool.length>=15);assert.ok(pool.every(item=>item.category===category&&item.minMinutes<=budget&&item.maxMinutes>=budget))}});
test('history is bounded to a pool cycle and filter reset can start clean',()=>{assert.deepEqual(nextHistory(['a','b','c'],'d',3),['b','c','d']);assert.equal(pickActivity([{id:'a'},{id:'b'}],[],()=>0).id,'a')});
test('malformed entries, ids, titles, durations, and categories fail',()=>{const valid={id:'good-id',title:'Good title',category:'move',minMinutes:20,idealMinutes:30,maxMinutes:60,note:'A real instruction.'};const options={minimumActivities:0,minimumCoverage:0};assert.match(validateActivities([{...valid,id:'BAD'}],options).join(),/invalid id/);assert.match(validateActivities([valid,{...valid}],options).join(),/duplicate id/);assert.match(validateActivities([valid,{...valid,id:'other',title:' GOOD---title '}],options).join(),/duplicate normalized title/);assert.match(validateActivities([{...valid,category:'danger'}],options).join(),/invalid category/);assert.match(validateActivities([{...valid,idealMinutes:10}],options).join(),/invalid durations/);assert.match(validateActivities([{...valid,title:'<script>'}],options).join(),/invalid title/);assert.match(validateActivities([{...valid,note:'TODO'}],options).join(),/invalid note/);assert.match(validateActivities([],options).join(),/non-empty/);assert.equal(normalizeTitle(' Good---title '),'good title')});
test('strict URL state accepts only supported compatible local values',()=>{const valid=parseUrlState('?minutes=45&category=move&activity=walk-new-turns',activities);assert.equal(valid.minutes,45);assert.equal(valid.category,'move');assert.equal(valid.activity?.id,'walk-new-turns');const bad=parseUrlState('?minutes=999&category=%3Cscript%3E&activity=walk-new-turns',activities);assert.deepEqual(bad,{minutes:90,category:'anything',activity:activities.find(x=>x.id==='walk-new-turns')});const incompatible=parseUrlState('?minutes=30&category=watch&activity=bake-simple',activities);assert.equal(incompatible.activity,null)});
test('URL activity state restores new catalog entries',()=>{const restored=parseUrlState('?minutes=120&category=connect&activity=question-jar',activities);assert.equal(restored.activity?.id,'question-jar');assert.equal(restored.category,'connect');assert.equal(restored.minutes,120)});
test('sharing text uses validated activity data and selected duration',()=>{assert.equal(shareText(activities[0],45),'I had 45 minutes. The internet told me to take a walk with three unfamiliar turns.')});
