import test from'node:test';import assert from'node:assert/strict';import{categories,configFromSearch,configKey,createPlan,items,normalizeConfig,options,searchFromConfig}from'../src/js/planner.js';
const spaces=[];for(let mask=0;mask<16;mask++)spaces.push(options.spaces.filter((_,i)=>mask&(1<<i)));
test('curated model has unique definitions and substantial coverage',()=>{assert.equal(new Set(items.map(x=>x.id)).size,items.length);assert.ok(items.length>=50);assert.equal(categories.length,13)});
test('broad deterministic matrix stays arithmetically valid',()=>{let count=0;for(const people of[1,8,25,75,200])for(const style of options.styles)for(const computer of options.computers)for(const rooms of[0,1,2,4])for(const selected of spaces)for(const level of options.levels){const plan=createPlan({people,style,computer,rooms,spaces:selected,level});count++;assert.ok(plan.itemCount>=20);assert.equal(new Set(plan.categories.flatMap(x=>x.items.map(y=>y.id))).size,plan.itemCount);let grandLow=0,grandHigh=0;for(const category of plan.categories){assert.equal(category.low,category.items.reduce((n,x)=>n+x.low,0));assert.equal(category.high,category.items.reduce((n,x)=>n+x.high,0));for(const item of category.items){assert.ok(Number.isInteger(item.quantity)&&item.quantity>0);assert.ok(Number.isFinite(item.low)&&Number.isFinite(item.high));assert.ok(item.low<=item.high)}grandLow+=category.low;grandHigh+=category.high}assert.equal(plan.low,grandLow);assert.equal(plan.high,grandHigh);assert.ok(plan.low<=plan.high)}assert.equal(count,11520)});
test('headcount, meetings and spaces affect the correct things',()=>{const one=createPlan({people:1,style:'individual',rooms:0,spaces:[],level:'lean'}),large=createPlan({people:200,style:'individual',rooms:4,spaces:['kitchen'],level:'lean'});const qty=(plan,id)=>plan.categories.flatMap(x=>x.items).find(x=>x.id===id)?.quantity;assert.equal(qty(one,'desks'),1);assert.equal(qty(large,'desks'),200);assert.ok(qty(large,'access-points')>qty(one,'access-points'));assert.equal(qty(one,'room-display'),undefined);assert.equal(qty(large,'room-display'),4);assert.equal(qty(one,'fridge'),undefined);assert.equal(qty(large,'fridge'),1)});
test('meeting rooms always include the required room kit',()=>{for(const level of options.levels){const ids=createPlan({rooms:2,level}).categories.flatMap(x=>x.items.map(y=>y.id));for(const id of['tables','meeting-chairs','room-display','speakerphone','room-connect'])assert.ok(ids.includes(id))}});
test('premium is selection and quantity logic, not a multiplier',()=>{const base={people:12,style:'hybrid',computer:'peripherals',rooms:2,spaces:['kitchen']},lean=createPlan({...base,level:'lean'}),premium=createPlan({...base,level:'premium'});assert.ok(premium.itemCount>lean.itemCount);const qty=(plan,id)=>plan.categories.flatMap(x=>x.items).find(x=>x.id===id)?.quantity;assert.ok(qty(premium,'monitors')>qty(lean,'monitors'));assert.ok(premium.categories.flatMap(x=>x.items).some(x=>x.id==='sit-stand'));assert.ok(!lean.categories.flatMap(x=>x.items).some(x=>x.id==='sit-stand'))});
test('URL parsing is validated and round trips',()=>{const c=normalizeConfig({people:25,style:'client',computer:'full',rooms:2,spaces:['reception','quiet'],level:'premium'});assert.deepEqual(configFromSearch(searchFromConfig(c)),c);assert.deepEqual(configFromSearch('?people=wat&style=%3Cbad%3E&rooms=99&spaces=kitchen.hack&level=nope'),{...normalizeConfig({}),rooms:4,spaces:['kitchen']})});
test('checklist identity is stable and configuration scoped',()=>{const a=normalizeConfig({people:8,spaces:['quiet','kitchen']}),b=normalizeConfig({people:8,spaces:['kitchen','quiet']});assert.equal(configKey(a),configKey(b));assert.notEqual(configKey(a),configKey({...a,people:9}))});
