import{analyzeText,rangesFor,summaryFor,MIN_INSIGHT_WORDS}from'./analyzer.js';
import{SAMPLE_TEXT}from'./sample.js';

const editor=document.querySelector('#draft'),empty=document.querySelector('#empty-state'),short=document.querySelector('#short-state'),results=document.querySelector('#results'),primary=document.querySelector('#primary'),wordList=document.querySelector('#word-list'),phraseList=document.querySelector('#phrase-list'),nearby=document.querySelector('#nearby'),review=document.querySelector('#review-text'),reviewTitle=document.querySelector('#review-title'),status=document.querySelector('#action-status');
let analysis=analyzeText(''),selection=null,timer;
const fmt=new Intl.NumberFormat('en');

function buttonFor(item){const button=document.createElement('button');button.type='button';button.className='result-row';button.dataset.key=item.key;button.dataset.type=item.type;button.setAttribute('aria-pressed',String(selection?.key===item.key&&selection?.type===item.type));const name=document.createElement('span');name.className='result-name';name.textContent=item.type==='phrase'?`“${item.label}”`:item.label;const metric=document.createElement('span');metric.className='result-count';metric.textContent=`${item.count}×`;const detail=document.createElement('span');detail.className='result-detail';detail.textContent=`${item.percent.toFixed(1)}% · about once every ${item.every} words`;button.append(name,metric,detail);button.addEventListener('click',()=>{selection=item;renderLists();renderReview();review.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'})});return button}

function fillList(element,items,fallback){element.replaceChildren();if(!items.length){const note=document.createElement('p');note.className='no-result';note.textContent=fallback;element.append(note);return}for(const item of items)element.append(buttonFor(item))}

function renderLists(){fillList(wordList,analysis.words,'No meaningful word habit stands out yet.');fillList(phraseList,analysis.phrases,'No obvious repeated phrases.');nearby.replaceChildren();if(analysis.nearby.length){const item=analysis.nearby[0],p=document.createElement('p');p.append('“',item.word,'” appears twice within ',String(item.distance),' words.');nearby.append(p)}else{const p=document.createElement('p');p.textContent='No unusually close repeat stands out.';nearby.append(p)}}

function renderReview(){review.replaceChildren();if(!analysis.text){review.textContent='Your marked-up review will appear here.';reviewTitle.textContent='MARKED COPY';return}const ranges=rangesFor(selection);reviewTitle.textContent=selection?`MARKED COPY · ${selection.count} ${selection.count===1?'MARK':'MARKS'}`:'MARKED COPY · CHOOSE A RESULT';if(!ranges.length){review.textContent=analysis.text;return}let cursor=0;for(const[start,end]of ranges){review.append(document.createTextNode(analysis.text.slice(cursor,start)));const mark=document.createElement('mark');mark.textContent=analysis.text.slice(start,end);mark.setAttribute('aria-label',`${mark.textContent}, repeated selection`);review.append(mark);cursor=end}review.append(document.createTextNode(analysis.text.slice(cursor)))}

function renderPrimary(){primary.replaceChildren();if(!analysis.top)return;const eyebrow=document.createElement('p');eyebrow.className='red-note';eyebrow.textContent=analysis.top.type==='phrase'?'YOU KEEP SAYING':'YOU REALLY LIKE';const quote=document.createElement('p');quote.className='primary-word';quote.textContent=`“${analysis.top.label}”`;const count=document.createElement('p');count.className='primary-count';count.textContent=`${analysis.top.count} TIMES`;const context=document.createElement('p');context.textContent=`About once every ${analysis.top.every} words.`;primary.append(eyebrow,quote,count,context)}

function update(){analysis=analyzeText(editor.value);if(selection){selection=[...analysis.words,...analysis.phrases].find(item=>item.key===selection.key&&item.type===selection.type)||null}const hasText=analysis.stats.characters>0;empty.hidden=hasText;short.hidden=!hasText||analysis.eligible;results.hidden=!analysis.eligible;document.querySelector('#word-count').textContent=fmt.format(analysis.stats.words);document.querySelector('#character-count').textContent=fmt.format(analysis.stats.characters);document.querySelector('#sentence-count').textContent=fmt.format(analysis.stats.sentences);document.querySelector('#reading-time').textContent=analysis.stats.readingMinutes?`${analysis.stats.readingMinutes} min`:'—';if(analysis.eligible){renderPrimary();renderLists()}renderReview()}

editor.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(update,90)});
document.querySelector('#example').addEventListener('click',()=>{editor.value=SAMPLE_TEXT;selection=null;update();editor.focus();status.textContent='Example loaded.'});
document.querySelector('#clear').addEventListener('click',()=>{editor.value='';selection=null;update();editor.focus();status.textContent='Draft cleared.'});
document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(summaryFor(analysis));status.textContent='Results copied.'}catch{status.textContent='Could not copy results.'}});
document.querySelector('#minimum').textContent=String(MIN_INSIGHT_WORDS);
document.querySelectorAll('[data-year]').forEach(node=>node.textContent=String(new Date().getFullYear()));
update();
