import test from'node:test';import assert from'node:assert/strict';import{DESTINATIONS,DESTINATION_MAP,LENGTHS,VIBES,ENERGIES}from'../src/js/data.js';import{recommend,rankedDestinations,candidateBand,cravingMatches}from'../src/js/scoring.js';
const explicit=VIBES.filter(v=>v!=='surprise');
test('expanded dataset and taxonomy have meaningful depth',()=>{assert.ok(DESTINATIONS.length>=180);assert.ok(explicit.length>=12&&explicit.length<=16);for(const vibe of explicit)assert.ok(DESTINATIONS.filter(d=>d.vibes.includes(vibe)).length>=25,`${vibe} coverage`)});
test('single, pair and triple craving scoring rewards coverage',()=>{for(const vibes of[['food'],['food','nightlife'],['culture','architecture','romantic']]){const p={length:'four-five',vibes,energy:'balanced'},ranked=rankedDestinations(p,4);assert.ok(ranked[0].matches.length>=Math.min(2,vibes.length));assert.ok(ranked[0].matches.length>=ranked.at(-1).matches.length)}});
test('all 20,736 seasonal preference combinations return compatible results',()=>{const groups=[...explicit.map(a=>[a])];for(let a=0;a<explicit.length;a++)for(let b=a+1;b<explicit.length;b++){groups.push([explicit[a],explicit[b]]);for(let c=b+1;c<explicit.length;c++)groups.push([explicit[a],explicit[b],explicit[c]])}groups.push(['surprise']);let total=0;for(const month of[1,4,7,10])for(const length of LENGTHS)for(const vibes of groups)for(const energy of ENERGIES){total++;const p={length,vibes,energy},d=recommend(p,{month});assert.ok(d);assert.ok(d.lengths.includes(length),`${month}/${length}/${vibes}/${energy}`);if(!vibes.includes('surprise'))assert.ok(cravingMatches(d,p).length>=1,`${vibes}: no match`)}assert.equal(total,20736)});
test('ten rerolls avoid repeats and stay relevant',()=>{for(const p of[{length:'weekend',vibes:['food','nightlife'],energy:'balanced'},{length:'four-five',vibes:['culture','architecture','romantic'],energy:'easy'},{length:'week',vibes:['nature','mountains','adventure'],energy:'adventure'}]){const seen=[];for(let turn=0;turn<10;turn++){const d=recommend(p,{month:7,seen,turn});assert.ok(!seen.includes(d.id));assert.ok(cravingMatches(d,p).length>=1);seen.push(d.id)}}});
test('Surprise Me respects trip length while energy remains influential',()=>{for(const month of[1,4,7,10])for(const length of LENGTHS)for(const energy of ENERGIES){const d=recommend({length,vibes:['surprise'],energy},{month});assert.ok(d.lengths.includes(length))}});
test('shared IDs remain strict and stable',()=>{assert.equal(DESTINATION_MAP.get('porto').place,'Porto');assert.equal(DESTINATION_MAP.get('florence').place,'Florence');assert.equal(DESTINATION_MAP.has('../porto'),false);assert.equal(DESTINATION_MAP.has('%00'),false)});
test('required human-sense combinations have deep bands',()=>{const cases=[['weekend',['food','nightlife'],'balanced',4],['weekend',['culture','food'],'easy',10],['weekend',['romantic','food'],'easy',4],['weekend',['charming','culture'],'easy',10],['four-five',['sun','relax'],'easy',1],['four-five',['culture','architecture'],'balanced',4],['four-five',['weird','hidden'],'balanced',10],['four-five',['food','culture','nightlife'],'balanced',10],['week',['nature','mountains'],'balanced',7],['week',['nature','adventure'],'adventure',7],['week',['sun','islands'],'easy',7],['week',['culture','food'],'balanced',10]];for(const[length,vibes,energy,month]of cases){const p={length,vibes,energy},band=candidateBand(p,month);assert.ok(band.length>=5,`${length}/${vibes}: ${band.length}`);assert.ok(cravingMatches(band[0].destination,p).length>=1)}});
