export const CATEGORIES = Object.freeze(['move','make','watch','learn','reset','outside','connect']);
export const BUDGETS = Object.freeze([30,45,60,90,120]);

const a=(id,title,category,minMinutes,idealMinutes,maxMinutes,note)=>Object.freeze({id,title,category,minMinutes,idealMinutes,maxMinutes,note});

export const activities=Object.freeze([
  a('walk-new-turns','Take a walk with three unfamiliar turns','move',30,45,120,'No pace target. Just notice where you end up.'),
  a('mobility-reset','Do a gentle full-body mobility session','move',20,30,60,'Keep it comfortable; this is movement, not a test.'),
  a('music-dance','Put on music and dance around the room','move',20,30,60,'Close the curtains if that helps.'),
  a('bodyweight-circuit','Complete a familiar bodyweight workout','move',25,45,75,'Choose movements you already know suit you.'),
  a('long-stretch','Stretch slowly from head to toe','move',20,30,50,'Give the tight bits time instead of forcing them.'),
  a('bike-loop','Take an easy bike ride','move',40,60,120,'Use a familiar safe route and leave the stopwatch alone.'),
  a('stairs-and-air','Walk outside, taking the stairs on the way','move',25,45,90,'A little effort, a lot of air.'),
  a('yoga-flow','Follow a yoga flow you already like','move',25,45,75,'Make space, move gently, stop if anything hurts.'),
  a('throw-catch','Play a casual throwing or catching game','move',30,45,90,'A ball is optional; improvisation counts.'),
  a('neighborhood-laps','Walk a few brisk neighborhood laps','move',30,60,120,'Turn back while it still feels good.'),
  a('freestyle-balance','Practice balance with a few simple standing drills','move',15,30,120,'Stay near a wall or sturdy chair and keep it easy.'),
  a('jump-rope-basics','Try a relaxed jump-rope session','move',15,30,120,'Short rounds and generous rests count.'),
  a('living-room-pilates','Do a beginner-friendly Pilates session','move',20,40,120,'Choose familiar movements and work at your own pace.'),
  a('hula-hoop-play','Play around with a hula hoop','move',15,30,120,'Learning to keep it going is half the fun.'),
  a('shadow-boxing','Do a light shadow-boxing session','move',15,30,120,'Keep the movements controlled and skip contact entirely.'),
  a('active-video-game','Play an active video game','move',20,45,120,'Clear some space before you start.'),
  a('floor-is-lava','Build a playful floor-is-lava route at home','move',20,35,120,'Keep every step low, stable, and sensible.'),
  a('learn-dance-step','Learn one dance step and put it into a song','move',20,40,120,'Awkward first attempts are the activity.'),
  a('gentle-core','Do a gentle core-strength session','move',15,30,120,'Use movements you know and stop before form slips.'),
  a('movement-dice','Assign six movements to a die and play','move',20,35,120,'Keep every option comfortable enough to repeat.'),
  a('indoor-obstacle-route','Make and complete a safe indoor movement route','move',20,40,120,'Go around furniture, never over anything risky.'),
  a('tai-chi-basics','Practice a short tai chi sequence','move',20,40,120,'Slow and approximate is perfectly acceptable.'),
  a('clean-to-one-album','Do active housework for one album','move',25,45,120,'Pick jobs that keep you moving, then stop with the music.'),
  a('playground-session','Use a nearby playground like a grown-up','move',25,45,120,'Choose sturdy equipment and keep it low-key.'),

  a('sketch-one-object','Sketch one ordinary object in unreasonable detail','make',25,45,75,'Pick the nearest thing. Looking closely is the point.'),
  a('write-tiny-story','Write a story that fits on one page','make',30,60,90,'Give it an ending, even a strange one.'),
  a('cook-from-scratch','Cook one simple thing from scratch','make',45,75,120,'Use what you have; novelty is optional.'),
  a('photo-theme','Take a ten-photo series around one theme','make',30,60,90,'Light, circles, red things—choose once and commit.'),
  a('paper-collage','Make a paper collage from scraps','make',30,60,90,'Old packaging and junk mail are valid materials.'),
  a('playlist-arc','Build a playlist with a beginning, middle, and end','make',25,45,75,'Sequence matters more than quantity.'),
  a('write-letter','Write someone a proper letter','make',30,45,75,'Sending it can be tomorrow’s problem.'),
  a('repair-small-thing','Repair one small thing you already own','make',30,60,120,'Choose a fix you can safely finish or pause.'),
  a('bake-simple','Bake something uncomplicated','make',60,90,120,'A familiar recipe is still making something.'),
  a('make-zine','Fold and fill a tiny one-sheet zine','make',45,75,120,'Eight little pages; no masterpiece required.'),
  a('invent-sandwich','Invent a sandwich or snack from what you have','make',15,30,120,'Give it a name if it earns one.'),
  a('paper-airplane-lab','Fold and test a few paper-airplane designs','make',20,40,120,'Change one thing between flights.'),
  a('record-tiny-song','Record a tiny song with whatever makes sound','make',20,45,120,'A voice memo is a studio today.'),
  a('decorate-container','Turn an empty container into something worth keeping','make',20,45,120,'Use paper, pens, tape, or whatever is already around.'),
  a('write-comic-strip','Make a short comic strip','make',20,45,120,'Stick figures have carried entire careers.'),
  a('fold-origami','Fold one origami model','make',20,40,120,'Start with ordinary paper and accept a wonky result.'),
  a('design-board-game','Prototype a tiny board game','make',25,60,120,'One page of rules and borrowed pieces are enough.'),
  a('remix-leftovers','Turn leftovers into a different meal','make',20,45,120,'Aim for satisfying, not restaurant-worthy.'),
  a('handmade-bookmark','Make a durable bookmark','make',15,30,120,'Cardboard, thread, or folded paper will do.'),
  a('write-monologue','Write and perform a two-minute monologue','make',25,50,120,'One character, one want, one take.'),
  a('build-card-tower','Build the best card tower you can','make',15,35,120,'Rebuilding after collapse is included.'),
  a('clay-small-object','Shape a small object from clay or dough','make',20,45,120,'Useful, decorative, or completely mysterious.'),
  a('design-personal-logo','Design a playful personal emblem','make',20,45,120,'Use three symbols that feel like you.'),
  a('map-imaginary-place','Draw a map of an imaginary place','make',20,50,120,'Add routes, odd landmarks, and at least one secret.'),

  a('sitcom-episodes','Watch a couple of sitcom episodes','watch',40,50,120,'Pick the show quickly. The decision is already mostly made.'),
  a('short-film','Watch one short film','watch',20,35,60,'Credits included. No second-screen scrolling.'),
  a('documentary-episode','Watch one documentary episode','watch',35,50,75,'One subject, one episode, then stop.'),
  a('concert-set','Watch a recorded live music set','watch',30,60,120,'Turn it up to a considerate volume.'),
  a('favorite-episode','Rewatch a favorite television episode','watch',25,45,70,'Comfort viewing is a legitimate genre.'),
  a('visual-essay','Watch a thoughtful video essay','watch',20,35,55,'Choose one, not an algorithmic queue.'),
  a('animation-selection','Watch a small selection of animated shorts','watch',25,45,75,'Different styles, one compact sitting.'),
  a('standup-special','Watch part or all of a comedy special','watch',40,65,120,'Stop when your available time does.'),
  a('making-of','Watch a behind-the-scenes feature','watch',30,50,120,'Craft is often more interesting than promotion.'),
  a('public-domain-classic','Watch a short public-domain classic','watch',45,75,120,'Try something older than your usual queue.'),
  a('music-videos-hour','Curate and watch a run of music videos','watch',20,45,120,'Pick an era, director, or mood instead of autoplay.'),
  a('travelogue','Watch a travelogue about somewhere unfamiliar','watch',20,45,120,'Enjoy the place without planning a trip.'),
  a('game-show','Watch a game-show episode and play along','watch',20,45,120,'Commit to your answers before the reveal.'),
  a('silent-film','Watch a silent film or a substantial excerpt','watch',20,50,120,'Notice how much story survives without dialogue.'),
  a('nature-camera','Watch a live nature camera or recorded wildlife footage','watch',20,45,120,'Let the slow stretches stay slow.'),
  a('sports-highlights','Watch highlights from a sport you rarely follow','watch',20,40,120,'Learn just enough context to care about the finish.'),
  a('stage-performance','Watch a recorded stage performance','watch',25,60,120,'Theatre, dance, circus, or spoken word all count.'),
  a('classic-commercials','Watch a collection of old commercials','watch',15,30,120,'Treat it as accidental cultural history.'),
  a('film-opening-scenes','Compare the opening scenes of three films','watch',25,45,120,'Notice what each one promises before the plot begins.'),
  a('home-video-night','Watch old home videos','watch',20,50,120,'Cringe is part of the archive.'),
  a('foreign-tv-sample','Try an episode of television from another country','watch',25,50,120,'Pick by premise and let subtitles do their job.'),
  a('magic-performance','Watch a recorded magic performance','watch',20,45,120,'Resist pausing to solve every method.'),
  a('award-winning-short','Watch a prize-winning short film','watch',15,35,120,'One complete story beats an hour of browsing.'),
  a('screen-saver-visuals','Put on slow visual art and actually watch it','watch',15,30,120,'Ambient animation, projections, or visualizers qualify.'),

  a('language-lesson','Complete one focused language lesson','learn',25,45,75,'Review counts. Fluency is not due today.'),
  a('instrument-practice','Practice an instrument with one narrow focus','learn',25,45,90,'One passage, rhythm, or technique is enough.'),
  a('tutorial-follow','Follow one practical beginner tutorial','learn',30,60,90,'Make the example alongside it.'),
  a('read-long-article','Read one long article carefully','learn',25,45,75,'One tab. Notes optional.'),
  a('museum-from-home','Explore one museum collection online','learn',30,60,90,'Follow one room, artist, or object trail.'),
  a('map-a-topic','Make a one-page map of a topic you are learning','learn',30,60,90,'Connections first; neatness later.'),
  a('recipe-technique','Learn one useful kitchen technique','learn',30,45,75,'Choose something you can practice with what is on hand.'),
  a('chess-puzzles','Work through a set of chess or logic puzzles','learn',20,40,70,'Stop before it turns into punishment.'),
  a('read-book-chapter','Read a substantial chapter of a nonfiction book','learn',30,60,100,'Underline only if it genuinely helps.'),
  a('mini-course-unit','Finish one unit of a course already started','learn',40,75,120,'No browsing for a better course.'),
  a('bird-identification','Learn to identify five local birds','learn',20,40,120,'Focus on shape, color, and one memorable clue.'),
  a('family-recipe-story','Learn the story behind a family recipe','learn',20,45,120,'Ask someone or inspect the notes and ingredients.'),
  a('keyboard-shortcuts','Learn five shortcuts for software you use','learn',15,30,120,'Practice each one enough to remember tomorrow.'),
  a('constellation-basics','Learn to recognize one constellation','learn',20,40,120,'A diagram indoors still counts if the sky disagrees.'),
  a('poem-close-read','Read one poem several times','learn',15,30,120,'Look up only the references that truly block you.'),
  a('how-object-works','Figure out how one everyday object works','learn',20,45,120,'Choose something safe to inspect without dismantling it.'),
  a('memory-palace','Build a small memory palace and test it','learn',20,45,120,'Ten items are enough for a proper experiment.'),
  a('geography-quiz','Learn a region through a blank-map quiz','learn',20,40,120,'Repeat once and enjoy the visible improvement.'),
  a('music-ear-training','Try a basic music ear-training exercise','learn',15,30,120,'Treat wrong answers as useful information.'),
  a('read-explainer','Read a clear explainer on a question you have','learn',20,45,120,'Write the answer in one sentence afterward.'),
  a('sign-language-phrases','Learn a handful of sign-language phrases','learn',20,40,120,'Use a source for the sign language used where you live.'),
  a('home-science-observation','Run a safe kitchen-table observation experiment','learn',20,45,120,'Try shadows, dissolving, sound, or surface tension—no flames.'),
  a('art-style-study','Learn how to spot one art or design style','learn',20,45,120,'Find three examples and name the shared clues.'),
  a('etymology-trail','Follow the origins of five ordinary words','learn',20,40,120,'Stop when the trail becomes a rabbit hole.'),

  a('phone-free-lie-down','Lie down somewhere comfortable without your phone','reset',20,30,60,'No objective. Ceiling inspection is allowed.'),
  a('proper-nap','Take a guilt-free nap','reset',25,35,60,'Set one alarm and let the rest wait.'),
  a('album-chair','Listen to an album from a chair','reset',30,50,90,'Nothing else at the same time.'),
  a('one-room-reset','Reset one room properly','reset',30,60,120,'Clean enough to feel different, then leave it.'),
  a('annoying-drawer','Sort the drawer you keep avoiding','reset',20,35,60,'One drawer means one drawer.'),
  a('long-shower','Take an unhurried shower and put on clean clothes','reset',25,40,60,'A small reset, fully completed.'),
  a('tomorrow-easier','Make tomorrow slightly easier','reset',25,45,120,'Prepare only the obvious friction points.'),
  a('tea-no-agenda','Make a drink and sit with no agenda','reset',20,35,60,'Looking out the window is an activity.'),
  a('digital-desktop','Clear your digital desktop and downloads','reset',25,45,120,'Delete carefully; organize only what matters.'),
  a('quiet-read-fiction','Read fiction somewhere comfortable','reset',30,60,120,'Let the book have the whole block.'),
  a('jigsaw-puzzle','Work on a jigsaw puzzle','reset',20,45,120,'Finishing is optional; finding edge pieces is progress.'),
  a('hand-wash-favorites','Hand-wash a few favorite clothes','reset',20,40,120,'Choose items that are actually safe to hand-wash.'),
  a('window-open-pause','Open a window and do absolutely nothing for a while','reset',15,30,120,'No breathing technique, streak, or lesson attached.'),
  a('paperwork-stack','Deal with one small stack of paperwork','reset',20,45,120,'File, recycle, or act; avoid creating a new pile.'),
  a('puzzle-book','Do a few pages of a puzzle book','reset',20,40,120,'Crosswords, mazes, and number puzzles all qualify.'),
  a('clothes-combination','Find three outfits from clothes you already own','reset',20,45,120,'Photograph the combinations and make future you grateful.'),
  a('soak-feet','Soak your feet and listen to something pleasant','reset',20,35,120,'Use comfortably warm water and nowhere else to be.'),
  a('fridge-shelf','Clean and reorganize one fridge shelf','reset',20,35,120,'Check dates, wipe it down, and stop at one shelf.'),
  a('memory-box','Sort one small box of keepsakes','reset',20,50,120,'Keep the stories; lose only what feels easy.'),
  a('no-input-hour','Spend time with no news, feeds, or entertainment','reset',20,45,120,'Boredom is allowed to finish its sentence.'),
  a('fresh-sheets','Change the bed and enjoy fresh sheets','reset',20,35,120,'The final five minutes are for lying on them.'),
  a('brain-dump','Put every loose thought onto one sheet of paper','reset',15,30,120,'Do not turn the list into a life overhaul.'),
  a('slow-breakfast','Make and eat an unhurried breakfast or snack','reset',20,45,120,'Sit down for it, even if the meal is simple.'),
  a('unsubscribe-session','Unsubscribe from unwanted email','reset',20,40,120,'Work from recent senders and avoid chasing inbox zero.'),

  a('explore-nearby','Explore nearby without choosing a destination','outside',30,60,120,'Keep it local, safe, and pleasantly aimless.'),
  a('bench-observation','Sit outside and watch the world happen','outside',20,35,75,'No need to document it.'),
  a('cloud-and-weather','Go outside and pay attention to the weather','outside',20,30,60,'Dress for the actual conditions.'),
  a('photo-walk','Take a slow photo walk','outside',30,60,120,'Photograph details, not landmarks.'),
  a('read-outside','Take something to read outside','outside',30,60,120,'A doorstep or balcony counts.'),
  a('sunset-or-sky','Find a safe open view of the sky','outside',25,45,90,'Daylight, clouds, or stars all qualify.'),
  a('outdoor-coffee','Have a drink outside with no agenda','outside',25,45,75,'Bought or homemade makes no difference.'),
  a('local-soundwalk','Take a sound-focused walk','outside',30,45,90,'Leave headphones off and notice the layers.'),
  a('garden-tend','Tend to plants or a small outdoor space','outside',25,50,90,'Water, prune, sweep, or simply inspect.'),
  a('different-route','Take the long way around somewhere familiar','outside',30,60,120,'The detour is the activity.'),
  a('chalk-drawing','Make a temporary chalk drawing outside','outside',20,40,120,'A small patch and washable chalk are plenty.'),
  a('collect-color-palette','Find a five-color palette in the world outside','outside',20,40,120,'Photograph colors; leave plants and objects where they are.'),
  a('outdoor-sketch','Sit outside and sketch what is in front of you','outside',20,45,120,'A doorstep view is worthy subject matter.'),
  a('window-shopping','Go window-shopping with no plan to buy','outside',25,50,120,'Judge displays, invent backstories, keep your wallet closed.'),
  a('public-art-hunt','Look for murals, statues, or odd bits of public art','outside',25,50,120,'One good discovery is enough.'),
  a('picnic-for-one','Take a tiny picnic outside','outside',20,45,120,'A snack on a bench absolutely qualifies.'),
  a('architecture-details','Photograph interesting architectural details','outside',25,50,120,'Doors, signs, tiles, and shadows beat famous buildings.'),
  a('outdoor-audio','Listen to one podcast episode outside','outside',25,50,120,'Choose a safe place where headphones make sense.'),
  a('litter-pick','Pick up litter in one small area','outside',20,40,120,'Use gloves or a grabber and leave anything unsafe alone.'),
  a('seasonal-check','Look for ten signs of the current season','outside',20,40,120,'Notice what changed since last month.'),
  a('fly-paper-kite','Make a simple paper kite or glider and test it outside','outside',25,50,120,'Use an open safe space away from roads and wires.'),
  a('outdoor-journal','Write one journal page outdoors','outside',20,40,120,'Describe where you are before writing about yourself.'),
  a('shadow-tracing','Trace and photograph interesting shadows','outside',20,35,120,'Use chalk only where it is permitted and washable.'),
  a('local-history-signs','Read the plaques and signs you normally pass','outside',20,45,120,'Let the neighborhood explain one thing about itself.'),

  a('call-someone','Call someone you have been meaning to call','connect',25,45,90,'No elaborate reason required.'),
  a('voice-note-catchup','Send a thoughtful voice-note catch-up','connect',20,30,50,'Say the thing properly instead of typing “soon.”'),
  a('card-game','Play a card or tabletop game','connect',30,60,120,'Choose something everyone already understands.'),
  a('shared-walk','Invite someone on a walk','connect',30,60,120,'Conversation tends to arrive on its own.'),
  a('cook-together','Make a simple meal with someone','connect',45,90,120,'Keep the menu easier than the company.'),
  a('family-photos','Look through old photos with someone','connect',30,60,100,'Let the stories take the time they take.'),
  a('help-small-task','Help someone with one small practical task','connect',30,60,90,'Agree on the finish line before starting.'),
  a('two-person-quiz','Make and trade a tiny quiz with someone','connect',25,45,75,'Five questions each is plenty.'),
  a('porch-conversation','Sit somewhere comfortable and have a proper chat','connect',30,60,120,'Phones away if everyone agrees.'),
  a('write-postcard','Write and address a postcard or note','connect',20,30,50,'A small hello still counts as contact.'),
  a('trade-recommendations','Trade three recommendations with someone','connect',15,30,120,'Books, snacks, games, songs—mixing categories is encouraged.'),
  a('co-op-video-game','Play a cooperative video game together','connect',25,60,120,'Choose teamwork over a complicated setup.'),
  a('teach-small-skill','Teach someone one small thing you know','connect',20,40,120,'Keep the lesson useful, short, and welcome.'),
  a('shared-playlist','Build a shared playlist one song at a time','connect',20,45,120,'Take turns and explain only the surprising choices.'),
  a('neighbor-hello','Have a proper chat with a neighbor','connect',15,30,120,'Keep it natural and respect their time.'),
  a('memory-interview','Ask someone about one vivid memory','connect',20,45,120,'Listen for details instead of racing to your own story.'),
  a('remote-snack-break','Have a video-call snack break with someone','connect',20,40,120,'No meeting agenda disguised as friendship.'),
  a('collaborative-story','Write a story by alternating sentences','connect',20,40,120,'Let each new sentence complicate the last one.'),
  a('swap-photos','Exchange five recent photos and explain them','connect',20,40,120,'Ordinary photos usually have the best stories.'),
  a('plan-free-hangout','Invite someone over for a deliberately unplanned hour','connect',25,60,120,'Tea and somewhere to sit are enough.'),
  a('read-aloud','Read something aloud to each other','connect',20,45,120,'A short story, essay, or absurd review will work.'),
  a('make-something-together','Make one small thing with someone','connect',25,55,120,'Use materials already available and share the decisions.'),
  a('question-jar','Make a question jar and take turns answering','connect',20,45,120,'Mix silly questions with ones worth pausing over.'),
  a('small-favor-message','Offer one specific small favor to someone','connect',15,30,120,'Make it concrete and easy for them to decline.'),
]);
