import test from 'node:test';import assert from 'node:assert/strict';import{calendarHours,durationParts,generateWeekends,plural,weekendDaysRemaining,weekendSnapshot,weekendState}from'../src/js/weekends.js';

test('weekends are generated from real Saturdays, not hardcoded',()=>{for(const year of[2024,2025,2026,2028]){const list=generateWeekends(year);assert.ok(list.length===52||list.length===53);assert.ok(list.every(w=>w.saturday.getDay()===6&&w.saturday.getFullYear()===year&&w.sunday.getDay()===0));for(let i=1;i<list.length;i++)assert.equal(list[i].saturday.getDate(),new Date(year,list[i-1].saturday.getMonth(),list[i-1].saturday.getDate()+7).getDate())}});
test('year beginning Saturday has 53 owned weekends',()=>{const list=generateWeekends(2022);assert.equal(list.length,53);assert.equal(list[0].saturday.getDate(),1);assert.equal(list.at(-1).saturday.getMonth(),11);assert.equal(list.at(-1).saturday.getDate(),31)});
test('normal and leap years derive the expected calendar',()=>{assert.equal(generateWeekends(2025).length,52);assert.equal(generateWeekends(2024).length,52);assert.ok(generateWeekends(2024).some(w=>w.saturday.getMonth()===1||w.sunday.getMonth()===1))});
test('Monday before and Friday immediately before include upcoming weekend',()=>{const mon=weekendSnapshot(new Date(2025,8,22,9)),fri=weekendSnapshot(new Date(2025,8,26,23,59,59));assert.equal(mon.isWeekend,false);assert.equal(fri.isWeekend,false);assert.equal(mon.next.saturday.getDate(),27);assert.equal(fri.next.saturday.getDate(),27);assert.ok(fri.countdownMs>0)});
test('exact Saturday midnight and Saturday daytime are current',()=>{for(const d of[new Date(2025,8,27,0),new Date(2025,8,27,14)]){const s=weekendSnapshot(d);assert.equal(s.isWeekend,true);assert.ok(s.currentOwned);assert.equal(weekendState(s.currentOwned,d),'current');assert.equal(s.countdownTarget.getDay(),1)}});
test('Sunday is current, while exact Monday completes it',()=>{const sun=weekendSnapshot(new Date(2025,8,28,14));assert.equal(sun.isWeekend,true);assert.equal(sun.weekendDaysLeft,27);const monday=weekendSnapshot(new Date(2025,8,29,0));assert.equal(monday.isWeekend,false);assert.equal(monday.completed.length,sun.completed.length+1);assert.equal(weekendState(sun.currentOwned,new Date(2025,8,29,0)),'completed')});
test('weekend days are independent of weekends-left multiplication',()=>{const sat=weekendSnapshot(new Date(2022,11,31,12));assert.equal(sat.weekendsLeft,1);assert.equal(sat.weekendDaysLeft,1);const sun=weekendSnapshot(new Date(2025,11,28,12));assert.equal(sun.weekendsLeft,1);assert.equal(sun.weekendDaysLeft,1)});
test('December/January crossover belongs to its Saturday year',()=>{const ending=generateWeekends(2022).at(-1);assert.equal(ending.saturday.getFullYear(),2022);assert.equal(ending.sunday.getFullYear(),2023);const dec31=weekendSnapshot(new Date(2022,11,31,12));assert.equal(dec31.last.saturday.getDate(),31);assert.equal(dec31.weekendDaysLeft,1);const jan1=weekendSnapshot(new Date(2023,0,1,12));assert.equal(jan1.isWeekend,true);assert.equal(jan1.currentOwned,null);assert.equal(jan1.weekendDaysLeft,105)});
test('year ending Sunday has a two-day final in-year weekend',()=>{const s=weekendSnapshot(new Date(2023,11,30,12));assert.equal(s.last.saturday.getDate(),30);assert.equal(s.last.sunday.getDate(),31);assert.equal(s.weekendDaysLeft,2)});
test('final weekend and last weekend are dynamic',()=>{const s=weekendSnapshot(new Date(2026,11,26,12));assert.equal(s.weekendsLeft,1);assert.equal(s.currentOwned,s.last);assert.equal(s.next,null)});
test('Jan 1 and Dec 31 choose their own local year',()=>{assert.equal(weekendSnapshot(new Date(2024,0,1)).year,2024);assert.equal(weekendSnapshot(new Date(2024,11,31,23,59)).year,2024);assert.equal(weekendSnapshot(new Date(2025,0,1)).year,2025)});
test('automatic rollover regenerates year and weekend collection',()=>{const before=weekendSnapshot(new Date(2022,11,31,23,59,59,999)),after=weekendSnapshot(new Date(2023,0,1));assert.equal(before.year,2022);assert.equal(before.weekends.length,53);assert.equal(after.year,2023);assert.equal(after.weekends.length,52)});
test('countdown is bounded and never negative',()=>{for(const d of[new Date(2025,0,1),new Date(2025,8,27),new Date(2025,8,29),new Date(2025,11,31,23,59)]){const s=weekendSnapshot(d);assert.ok(s.countdownMs>=0);assert.deepEqual(Object.values(durationParts(s.countdownMs)).every(v=>v>=0),true)}assert.deepEqual(durationParts(-10),{days:0,hours:0,minutes:0,seconds:0})});
test('DST weekend uses local boundaries rather than fixed 48 hours',()=>{const zone=process.env.TZ;const dates=zone==='America/New_York'?[new Date(2025,2,8),new Date(2025,2,10)]:[new Date(2025,2,29),new Date(2025,2,31)];assert.equal(calendarHours(...dates),47);const snap=weekendSnapshot(new Date(dates[0].getFullYear(),dates[0].getMonth(),dates[0].getDate(),12));assert.equal(snap.currentEnd.getTime(),dates[1].getTime())});
test('singular and plural wording',()=>{assert.equal(plural(1,'weekend'),'1 weekend');assert.equal(plural(2,'weekend'),'2 weekends');assert.equal(plural(0,'day'),'0 days')});
test('invalid inputs are rejected',()=>{assert.throws(()=>weekendSnapshot(new Date(NaN)),/valid date/);assert.throws(()=>generateWeekends(2025.5),/calendar year/)});
